/**
 * YouTube Subtitle Translator - Background Service Worker
 * Handles Multi-Engine Translation (Google Translate, YouTube Native, MyMemory, Google Cloud API),
 * with dual-layer caching, automatic failover, and settings synchronization.
 */

// In-memory cache for translations to reduce API calls and improve performance
const translationCache = new Map();
const MAX_CACHE_SIZE = 4000;

// Default configuration settings
const DEFAULT_SETTINGS = {
  enabled: true,
  displayMode: 'bilingual', // 'bilingual' | 'vietnamese_only' | 'off'
  translationService: 'google', // 'google' | 'youtube' | 'mymemory' | 'google_cloud'
  translateAutoGenerated: true, // Cho phép dịch phụ đề tạo tự động (ASR) của YouTube
  sourceLang: 'auto',
  targetLang: 'vi',
  fontSize: 20,
  fullscreenOptimize: true, // Auto-scale subtitle size in fullscreen mode
  fullscreenScaleMode: 'sync_yt', // 'sync_yt' | '1.25' | '1.4' | '1.5' | '1.75' | '2.0' | 'custom'
  fullscreenCustomSize: 32, // Custom font size when mode is 'custom'
  fontColor: '#FFFFFF', // Clean white matching native YouTube subtitle color
  originalColor: '#FFFFFF', // Soft light gray/white for original subtitle in bilingual mode
  bgOpacity: 75, // 75% dark backdrop (YouTube native standard)
  subPosition: 'bottom', // 'bottom' | 'top'
  subBottomOffset: 0, // 0 = automatic responsive elevation above player controls
  hideOriginalNative: true, // Hide YouTube's native subtitle render to avoid overlap
  customApiKey: '', // Optional Google Cloud Translation API key
  geminiApiKey: '', // Optional Google Gemini AI API key (free tier)
  geminiModel: 'gemini-3.5-flash-lite', // 'gemini-3.5-flash-lite' | 'gemini-3.5-flash'
  geminiRpdLimit: 500, // 500 RPD (Google AI Studio Free) | 1500 RPD (Google Cloud Tier 1)
  geminiStyle: 'auto', // 'auto' | 'lyrics' | 'news' | 'casual'
  geminiPronounRole: 'auto', // 'auto' | 'female' | 'male' | 'neutral'
  githubRepo: 'NgocThachTN/YTSubTranslateExtension', // GitHub repository for release updates
};

// Initialize default settings upon installation
chrome.runtime.onInstalled.addListener(async () => {
  try {
    const existing = await chrome.storage.sync.get(Object.keys(DEFAULT_SETTINGS));
    const toSet = {};
    for (const [key, value] of Object.entries(DEFAULT_SETTINGS)) {
      if (existing[key] === undefined) {
        toSet[key] = value;
      }
    }
    // Auto-migrate legacy 1.5, 2.0 or undefined models to gemini-3.5-flash-lite
    if (existing.geminiModel && (existing.geminiModel.includes('1.5') || existing.geminiModel.includes('2.0'))) {
      toSet.geminiModel = 'gemini-3.5-flash-lite';
    }
    // Migrate legacy default 60 to 0
    if (existing.subBottomOffset === 60) {
      toSet.subBottomOffset = 0;
    }
    if (Object.keys(toSet).length > 0) {
      await chrome.storage.sync.set(toSet);
    }
  } catch (err) {
    console.error('[YT Sub Translate] Failed to initialize settings:', err);
  }
});

/**
 * Decode HTML entities like &quot;, &#39;, &amp;, &lt;, &gt;
 */
function decodeHtmlEntities(str) {
  if (!str) return '';
  return str
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'")
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&#(\d+);/g, (_, code) => String.fromCharCode(code));
}

/**
 * Translate text using Google Cloud Translation API (if API Key provided)
 */
async function translateWithGoogleCloudApi(text, sourceLang, targetLang, apiKey) {
  const url = `https://translation.googleapis.com/language/translate/v2?key=${encodeURIComponent(apiKey)}`;
  const body = {
    q: text,
    target: targetLang,
    format: 'text',
  };
  if (sourceLang && sourceLang !== 'auto') {
    body.source = sourceLang;
  }

  const response = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  });

  if (!response.ok) {
    const errText = await response.text();
    throw new Error(`Google Cloud API error (${response.status}): ${errText}`);
  }

  const data = await response.json();
  if (data?.data?.translations?.[0]?.translatedText) {
    return decodeHtmlEntities(data.data.translations[0].translatedText);
  }
  throw new Error('Invalid response structure from Google Cloud API');
}

/**
 * Translate text using Google Translate free endpoint (with automatic fast failover)
 */
async function translateWithFreeGoogleEndpoint(text, sourceLang, targetLang) {
  const sl = sourceLang || 'auto';
  const tl = targetLang || 'vi';

  // Primary endpoint: gtx single
  try {
    const url = `https://translate.googleapis.com/translate_a/single?client=gtx&sl=${encodeURIComponent(sl)}&tl=${encodeURIComponent(tl)}&dt=t&q=${encodeURIComponent(text)}`;
    const response = await fetch(url, { keepalive: true });
    if (response.ok) {
      const data = await response.json();
      if (Array.isArray(data) && Array.isArray(data[0])) {
        const translatedText = data[0]
          .map((item) => (Array.isArray(item) && item[0] ? item[0] : ''))
          .join('');
        if (translatedText && translatedText.trim()) {
          return decodeHtmlEntities(translatedText);
        }
      }
    }
  } catch (err) {
    console.warn('[YT Sub Translate] Primary gtx endpoint failed, trying backup...', err);
  }

  // Backup fast endpoint 1: dict-chrome-ex
  try {
    const backupUrl = `https://clients5.google.com/translate_a/t?client=dict-chrome-ex&sl=${encodeURIComponent(sl)}&tl=${encodeURIComponent(tl)}&q=${encodeURIComponent(text)}`;
    const backupRes = await fetch(backupUrl, { keepalive: true });
    if (backupRes.ok) {
      const backupData = await backupRes.json();
      const result = Array.isArray(backupData) ? backupData[0] : backupData;
      if (result && typeof result === 'string' && result.trim()) {
        return decodeHtmlEntities(result.trim());
      }
    }
  } catch (err) {
    console.warn('[YT Sub Translate] Backup dict-chrome-ex endpoint failed, trying secondary...', err);
  }

  // Backup fast endpoint 2: gtx alternate
  try {
    const backup2Url = `https://translate.googleapis.com/translate_a/t?client=gtx&sl=${encodeURIComponent(sl)}&tl=${encodeURIComponent(tl)}&q=${encodeURIComponent(text)}`;
    const backup2Res = await fetch(backup2Url, { keepalive: true });
    if (backup2Res.ok) {
      const backup2Data = await backup2Res.json();
      const result2 = Array.isArray(backup2Data) ? backup2Data[0] : backup2Data;
      if (result2 && typeof result2 === 'string' && result2.trim()) {
        return decodeHtmlEntities(result2.trim());
      }
    }
  } catch (_) {}

  throw new Error('All Google translation endpoints failed');
}

/**
 * Fast script detection for CJK, Cyrillic, Arabic, etc.
 */
function detectScriptLanguage(text) {
  if (!text) return '';
  if (/[\u3040-\u309F\u30A0-\u30FF]/.test(text)) return 'ja';
  if (/[\uAC00-\uD7AF\u1100-\u11FF]/.test(text)) return 'ko';
  if (/[\u4E00-\u9FFF\u3400-\u4DBF]/.test(text)) return 'zh';
  if (/[\u0400-\u04FF]/.test(text)) return 'ru';
  if (/[\u0600-\u06FF]/.test(text)) return 'ar';
  if (/[\u0E00-\u0E7F]/.test(text)) return 'th';
  if (/[\u0370-\u03FF]/.test(text)) return 'el';
  if (/[\u0590-\u05FF]/.test(text)) return 'he';
  return '';
}

/**
 * Translate text using MyMemory Translation API (Free Translation Memory engine)
 */
async function translateWithMyMemory(text, sourceLang, targetLang) {
  let sl = sourceLang === 'auto' ? '' : sourceLang;
  if (!sl) {
    sl = detectScriptLanguage(text) || 'en';
  }
  const tl = targetLang || 'vi';
  const pair = `${sl}|${tl}`;
  const url = `https://api.mymemory.translated.net/get?q=${encodeURIComponent(text)}&langpair=${encodeURIComponent(pair)}`;

  const res = await fetch(url, { keepalive: true });
  if (!res.ok) {
    throw new Error(`MyMemory HTTP ${res.status}`);
  }

  const data = await res.json();
  const rawTrans = data?.responseData?.translatedText;
  if (rawTrans && typeof rawTrans === 'string') {
    const decoded = decodeHtmlEntities(rawTrans).trim();
    const upper = decoded.toUpperCase();
    const isWarning = upper.includes('MYMEMORY WARNING') || 
                      upper.includes('INVALID LANGUAGE PAIR') || 
                      upper.includes('NO QUERY SPECIFIED') ||
                      upper.includes('DAILY LIMIT') ||
                      upper.includes('QUERY LENGTH LIMIT');
    const isUntranslated = decoded.toLowerCase() === text.trim().toLowerCase();
    if (!isWarning && !isUntranslated && decoded.length > 0) {
      return decoded;
    }
  }
  throw new Error('MyMemory translation invalid, untranslated or quota exceeded');
}

/**
 * Supported Gemini API models & transparent fallback chain
 * Retains gemini-3.5-flash-lite as primary preference while ensuring zero 404 failures
 */
let activeWorkingGeminiModel = null;
const GEMINI_CANDIDATE_MODELS = [
  'gemini-3.5-flash-lite',
  'gemini-3.5-flash',
  'gemini-2.5-flash',
  'gemini-2.0-flash',
  'gemini-2.0-flash-lite',
  'gemini-1.5-flash'
];

function resolveGeminiModel(model) {
  if (!model) return 'gemini-3.5-flash-lite';
  if (model.includes('3.5-flash-lite') || model.includes('flash-lite') || model.includes('lite')) return 'gemini-3.5-flash-lite';
  if (model.includes('3.5-flash') || model.includes('3.5')) return 'gemini-3.5-flash';
  return model;
}

/**
 * Extract artist name if explicitly tagged in videoContext
 */
/**
 * Parse structured video context
 */
function parseVideoContext(videoContext = '') {
  const result = {
    genre: '',
    artist: '',
    guest: '',
    show: '',
    channel: '',
    title: videoContext
  };

  const genreMatch = videoContext.match(/Genre:\s*([^\|]+)/i);
  if (genreMatch) result.genre = genreMatch[1].trim().toLowerCase();

  const artistMatch = videoContext.match(/Artist:\s*([^\|]+)/i);
  if (artistMatch) result.artist = artistMatch[1].trim();

  const guestMatch = videoContext.match(/Guest\/Figure:\s*([^\|]+)/i);
  if (guestMatch) result.guest = guestMatch[1].trim();

  const showMatch = videoContext.match(/Show:\s*([^\|]+)/i);
  if (showMatch) result.show = showMatch[1].trim();

  const channelMatch = videoContext.match(/Channel:\s*([^\|]+)/i);
  if (channelMatch) result.channel = channelMatch[1].trim();

  const titleMatch = videoContext.match(/Title:\s*([^\|]+)/i);
  if (titleMatch) result.title = titleMatch[1].trim();

  return result;
}

/**
 * Determine effective video genre (lyrics | reality_show | news | casual)
 */
function resolveEffectiveGenre(requestedStyle = 'auto', videoContext = '') {
  if (requestedStyle && requestedStyle !== 'auto') {
    if (requestedStyle === 'lyrics') return 'lyrics';
    if (requestedStyle === 'reality') return 'reality_show';
    if (requestedStyle === 'news') return 'news';
    if (requestedStyle === 'casual') return 'casual';
  }

  const meta = parseVideoContext(videoContext);
  if (meta.genre) {
    if (meta.genre === 'music') return 'lyrics';
    if (meta.genre === 'reality_show') return 'reality_show';
    if (meta.genre === 'news') return 'news';
  }

  const lower = (videoContext || '').toLowerCase();
  if (/\b(bbc|cnn|vtv|cnbc|bloomberg|reuters|news|thời sự|bản tin|phóng sự|documentary|điều tra)\b/i.test(lower)) {
    return 'news';
  }
  if (/\b(running man|knowing bros|2 ngày 1 đêm|talkshow|podcast|phỏng vấn|interview|hot ones|the tonight show|game show|weekly idol|amazing saturday|ep\.\s*\d+|tập\s*\d+|show thực tế)\b|乃木坂工事中|nogizaka under construction|そこ曲がったら|日向坂で会いましょう|乃木坂どこへ|スター誕生|akbingo|サヨナラ毛利さん|モニタリング|水曜日のダウンタウン|ロンドンハーツ|アメトーーク|しゃべくり007|それsnow man|vs嵐|嵐にしやがれ|バラエティ|月曜から夜ふかし/i.test(videoContext || '')) {
    return 'reality_show';
  }
  if (/\b(mv|official music video|official video|lyric video|lyrics|audio|visualizer|m\/v|cover|remix|ft\.|feat\.|nhạc|bài hát|ca khúc|ost|soundtrack|live session|single|album|op|ed|theme|vocal|song|instrumental)\b|♪|♫|主題歌|挿入歌|楽曲|新曲|メドレー|乃木坂46|櫻坂46|日向坂46|欅坂46|akb48|ske48|nmb48|hkt48|=love|≠me|≒joy|モーニング娘|ももいろクローバー|ヨルシカ|ずとまよ|ずっと真夜中|結束バンド|初音ミク/i.test(videoContext || '')) {
    return 'lyrics';
  }

  return 'casual';
}

/**
 * Extract primary artist, guest or figure name from videoContext
 */
function extractPrimaryFigure(videoContext = '') {
  const meta = parseVideoContext(videoContext);
  return meta.artist || meta.guest || meta.show || meta.channel || '';
}

/**
 * Detect figure gender from video title, channel name, or metadata
 */
function detectFigureGender(videoContext = '') {
  const text = (videoContext || '').toLowerCase();
  const femalePatterns = [
    // Global & US-UK Female Artists
    /\b(laufey|aimer|yoasobi|zutomayo|yorushika|milet|claris|chappell roan|gracie abrams|sabrina carpenter|olivia dean|beabadoobee|billie eilish|olivia rodrigo|taylor swift|adele|ariana grande|dua lipa|katy perry|rihanna|lady gaga|beyonc[eé]|selena gomez|mariah carey|whitney houston|celine dion|avril lavigne|camila cabello|shakira|sia|lana del rey|halsey|miley cyrus|demi lovato|carly rae jepsen|bebe rexha|ellie goulding|kesha|alessia cara|lorde|anne-marie|madonna|britney spears|tate mcrae|sza|doja cat|cardi b|megan thee stallion|renee rapp|madison beer|dove cameron|raye|tinashe|kali uchis|rosal[ií]a|karol g|anitta|clairo|phoebe bridgers|lucy dacus|alicia keys|norah jones|amy winehouse|bjork|florence welch|katseye)\b/i,
    // Japanese Female Artists & Groups
    /\b(ado|lisa|reona|ikura|suis|acaね|daoko|chanmina|awich|yama|minami|sayuri|majiko|tuyu|eir aoi|kano|hanatan|nano|utada hikaru|utada|ayumi hamasaki|namie amuro|yui|kana nishino|aimyon|aoi teshima|chihiro onitsuka|mika nakashima|chico with honeyworks|honeyworks|supercell|atashi|clariS|akb48|nogizaka46|sakurazaka46|hinatazaka46|babymetal|ske48|nmb48|hkt48|ngt48|stu48|perfume|miwa|shishamo|scandal|silent siren|tamaki nami|hitomi shimatani|uru|mai kuraki|zard|mizuki nana|hayashibara megumi|kana hanazawa|inori minase|saori hayami|maaya sakamoto|angela aki)\b|乃木坂46|櫻坂46|日向坂46|欅坂46|akb48|ske48|nmb48|hkt48|ngt48|stu48|=love|≠me|≒joy|坂道|モーニング娘|ももいろクローバーz|ヨルシカ|ずとまよ|ずっと真夜中でいいのに|結束バンド|初音ミク/i,
    // Korean Female Artists & Girl Groups
    /\b(iu|taeyeon|ros[eé]|jennie|jisoo|lisa|blackpink|twice|aespa|ive|newjeans|le sserafim|red velvet|itzy|gidle|\(g\)i-dle|illit|babymonster|nmixx|stayc|kiss of life|meovv|chungha|sunmi|hwasa|lee hi|heize|bol4|davichi|mamamoo|sistar|girls' generation|snsd|kara|2ne1|apink|exid|oh my girl|fromis_9|loona|triples|boa|hyuna|somi|kwon eun bi|yena|chuu)\b/i,
    // Vietnamese Female Artists & Celebrities
    /\b(hòa minzy|hoa minzy|trang pháp|mỹ tâm|hồ ngọc hà|đông nhi|bích phương|hoàng thùy linh|min|amee|bảo anh|tóc tiên|hiền hồ|phương ly|lyly|tlinh|orange|suni hạ linh|văn mai hương|phương mỹ chi|vũ cát tường|hà nhi|lâm bảo ngọc|thùy chi|myra trần|uyên linh|lệ quyên|mỹ linh|hồng nhung|trần thu hà|hà trần|hương tràm|khổng tú quỳnh|thanh hà|như quỳnh|phi nhung|cẩm ly|minh tuyết|phương thanh|siu black|đoan trang|bảo thy|thùy lâm|giang hồng ngọc|pháo|marzuz|muộii|hồng thanh|hoàng yến chibi|mie|suboi|vũ phụng tiên|nguyên hà|phùng khánh linh|emily|liz kim cương|han sara|thu phương|lưu hương giang|minh hằng|diệp lâm anh|thúy ngân|lan ngọc|ninh dương lan ngọc|hari won|lâm vỹ dạ|sam|khả như)\b/i,
    // Chinese / Mandopop Female Artists
    /\b(đặng tử kỳ|g\.e\.m\.|gem|teresa teng|faye wong|vương phi|jolin tsai|thái y lâm|cyndi wang|vương tâm lăng|angela zhang|trương thiều hàm|fish leong|lương tĩnh như|a-lin|karen mok|mạc văn úy|hebe tien|điền phó chân|s\.h\.e|rainie yang|dương thừa lâm|liu yuxin|lexie liu|curley g)\b/i,
    // Variety Hosts Female
    /\b(ellen|oprah|drew barrymore|kelly clarkson|song ji hyo|jeon so min)\b/i
  ];
  const malePatterns = [
    // Global & US-UK Male Artists
    /\b(keshi|joji|stephen sanchez|conan gray|jeremy zucker|alec benjamin|ed sheeran|charlie puth|bruno mars|justin bieber|the weeknd|post malone|drake|shawn mendes|sam smith|harry styles|zayn|eminem|maroon 5|coldplay|benson boone|teddy swims|noah kahan|hozier|luke combs|morgan wallen|zach bryan|jack harlow|kendrick lamar|j\. cole|travis scott|kanye west|tyler, the creator|mac miller|juice wrld|xxxtentacion|lil nas x|bad bunny|peso pluma|david kushner|dean lewis|lewis capaldi|calum scott|james arthur|john legend)\b/i,
    // Japanese Male Artists & Bands
    /\b(fujii kaze|kenshi yonezu|vaundy|yuuri|eve|official hige dandism|king gnu|radwimps|back number|mrs\. green apple|asian kung-fu generation|bump of chicken|spyair|one ok rock|tani yuuki|imase|gen hoshino|tk from ling tosite sigure|hitorie|sukima switch|wacci|novelbright)\b/i,
    // Korean Male Artists & Boy Groups
    /\b(bts|jungkook|jimin|suga|exo|baekhyun|kai|stray kids|seventeen|bigbang|g-dragon|txt|tomorrow x together|enhypen|riize|zerobaseone|zb1|boynextdoor|tws|ateez|the boyz|treasure|monsta x|nct|nct 127|nct dream|wayv|shinee|taemin|wonho|woodz|crush|dpr ian|dpr live|zion\.t|loco|gray|sik-k|beenzino|epik high)\b/i,
    // Vietnamese Male Artists
    /\b(sơn tùng m-tp|sơn tùng|soobin hoàng sơn|soobin|jack|k-icm|erik|đức phúc|noo phước thịnh|hà anh tuấn|vũ\.|vũ|hoàng dũng|quân a\.p|trịnh thăng bình|phan mạnh quỳnh|trung quân|trung quân idol|bùi anh tuấn|quốc thiên|lân nhã|đan trường|tuấn hưng|justatee|rhymastic|đen vâu|đen|b ray|wren evans|mono|grey d|tăng duy tân|lê bảo bình|khắc việt|anh tú|lou hoàng|onlyc|kai đinh|hứa kim tuyền|bùi công nam|phạm hồng phước|nguyễn trần trung quân|bằng kiều|quang dũng|quang lê|trọng tấn|hieuthuhai|hieu thu hai|rhyder|quang hùng masterd|captain boy|wean|hurrykng|pháp kiều|negav|ali hoàng dương|isaac|song luân|gin tuấn kiệt|kay trần|cường seven|s\.t sơn thạch|st sơn thạch|bb trần|duy khánh|cris phan|trấn thành|trường giang|đại nghĩa|ngô kiến huy|jun phạm|lê dương bảo lâm|karik|wowy)\b/i,
    // Chinese / Mandopop Male Artists
    /\b(châu kiệt luân|jay chou|jj lin|lâm tuấn kiệt|eason chan|trần dịch tấn|wang leehom|vương lực hoành|joker xue|tiết chi khiêm|eric chou|châu hưng triết|hua chenyu|hoa hoa|hoa thần vũ|lay zhang|trương nghệ hưng|jackson wang|vương gia nhĩ|zhou shen|châu thâm|mayday|ngũ nguyệt thiên)\b/i,
    // Variety Hosts Male
    /\b(jimmy fallon|jimmy kimmel|stephen colbert|james corden|graham norton|joe rogan|conan o'brien|seth meyers|gordon ramsay|yoo jae suk|kang ho dong|shin dong yup|kim jong kook|haha|lee kwang soo|ji suk jin|yang se chan|lee soo geun|seo jang hoon|kim hee chul|min kyung hoon)\b/i
  ];

  for (const p of femalePatterns) {
    if (p.test(text)) return 'female';
  }
  for (const p of malePatterns) {
    if (p.test(text)) return 'male';
  }

  // Perspective clues in song title if artist not directly matched
  if (/\b(trái tim anh|anh đau|cho anh|với anh|bên anh|anh nhớ em|anh yêu em|anh xin lỗi|vì anh|anh muốn|chàng trai|chú rể)\b/i.test(text)) {
    return 'male';
  }
  if (/\b(trái tim em|em đau|cho em|với em|bên em|em nhớ anh|em yêu anh|em xin lỗi|vì em|em muốn|cô gái|cô dâu|nàng thơ)\b/i.test(text)) {
    return 'female';
  }

  return '';
}

// Session-level anchor map to guarantee 100% consistent perspective across all video lines
const videoRoleAnchor = new Map();
const MAX_ANCHOR_CACHE = 1000;

// Restore cached video anchors from session storage upon service worker startup
try {
  if (chrome.storage && chrome.storage.session) {
    chrome.storage.session.get(null).then((items) => {
      if (items) {
        for (const [k, v] of Object.entries(items)) {
          if (k.startsWith('role_') && typeof v === 'string') {
            videoRoleAnchor.set(k.slice(5), v);
          }
        }
      }
    }).catch(() => {});
  }
} catch (_) {}

function getVideoAnchorKey(videoContext = '') {
  if (!videoContext) return 'default';
  const match = videoContext.match(/Title:\s*([^\|]+)/i) || videoContext.match(/Artist:\s*([^\|]+)/i) || videoContext.match(/Show:\s*([^\|]+)/i);
  if (match) return match[1].trim().toLowerCase();
  return videoContext.slice(0, 80).toLowerCase().trim();
}

function resolveSongPronounRole(requestedRole, videoTitle, effectiveGenre = 'lyrics') {
  if (requestedRole && requestedRole !== 'auto') {
    return requestedRole;
  }

  const key = getVideoAnchorKey(videoTitle);
  if (videoRoleAnchor.has(key) && videoRoleAnchor.get(key) !== 'auto') {
    return videoRoleAnchor.get(key);
  }

  const detected = detectFigureGender(videoTitle);
  if (detected) {
    if (videoRoleAnchor.size >= MAX_ANCHOR_CACHE) {
      videoRoleAnchor.delete(videoRoleAnchor.keys().next().value);
    }
    videoRoleAnchor.set(key, detected);
    try {
      if (chrome.storage && chrome.storage.session) {
        chrome.storage.session.set({ [`role_${key}`]: detected }).catch(() => {});
      }
    } catch (_) {}
    return detected;
  }

  return 'auto';
}

function anchorRoleFromTranslation(videoTitle, translatedText) {
  const key = getVideoAnchorKey(videoTitle);
  if (!key) return;
  if (videoRoleAnchor.has(key) && videoRoleAnchor.get(key) !== 'auto') return;

  const text = (translatedText || '').toLowerCase();
  // Female singer signals (xưng em, gọi anh hoặc tâm sự phái nữ)
  const femaleSignals = (text.match(/\b(em yêu anh|em nhớ anh|nhớ anh|yêu anh|bên anh|gần anh|đợi anh|chờ anh|cần anh|vì anh|với anh|của anh|anh ơi|cho em|với em|của em|chính em|bản thân em|em nghĩ|em thấy|em muốn|em biết|em khóc|em mơ|em sợ|em bước|em đau|em chẳng|em không|em đã|em sẽ|em quay về|em ra đi|em buông tay|cô gái|nàng thơ|cô ấy)\b/g) || []).length;
  // Male singer signals (xưng anh, gọi em hoặc tâm sự phái nam)
  const maleSignals = (text.match(/\b(anh yêu em|anh nhớ em|nhớ em|yêu em|bên em|gần em|đợi em|chờ em|cần em|vì em|với em|của em|em ơi|cho anh|với anh|của anh|chính anh|bản thân anh|anh nghĩ|anh thấy|anh muốn|anh biết|anh khóc|anh mơ|anh sợ|anh bước|anh đau|anh chẳng|anh không|anh đã|anh sẽ|anh quay về|anh ra đi|anh buông tay|chàng trai|anh ấy)\b/g) || []).length;

  let chosenRole = '';
  if (femaleSignals > 0 && femaleSignals >= maleSignals) {
    chosenRole = 'female';
  } else if (maleSignals > 0 && maleSignals > femaleSignals) {
    chosenRole = 'male';
  }

  if (chosenRole) {
    if (videoRoleAnchor.size >= MAX_ANCHOR_CACHE) {
      videoRoleAnchor.delete(videoRoleAnchor.keys().next().value);
    }
    videoRoleAnchor.set(key, chosenRole);
    try {
      if (chrome.storage && chrome.storage.session) {
        chrome.storage.session.set({ [`role_${key}`]: chosenRole }).catch(() => {});
      }
    } catch (_) {}
  }
}

// Session-level pronoun & relationship summary for Reality Shows, Variety Shows, and Vlogs
const videoPronounSummary = new Map();

function updatePronounSummaryFromTranslation(videoTitle, translatedBatchText, effectiveGenre) {
  if (!videoTitle || !translatedBatchText) return;
  const key = getVideoAnchorKey(videoTitle);
  if (!key) return;

  const textLower = translatedBatchText.toLowerCase();

  if (effectiveGenre === 'reality_show') {
    const isJpIdol = /(乃木坂|櫻坂|日向坂|akb48|ske48|nmb48|hkt48|工事中|そこ曲がったら|日向坂で会いましょう|スター誕生|モニタリング|水曜日のダウンタウン|ロンドンハーツ)/i.test(videoTitle);
    if (isJpIdol) {
      videoPronounSummary.set(key, 'Idol members address themselves as "em", address MCs as "anh [Tên]". MCs address members as "em / mấy đứa", address viewers as "quý vị / mọi người". Keep lively cute reactions ("Hả?!", "Toang rồi!").');
      return;
    }

    const hasAudience = /\b(quý vị|quý khán giả|mọi người|các bạn)\b/.test(textLower);
    const hasAnhEm = /\b(anh|em|chị)\b/.test(textLower);
    const hasCauTo = /\b(cậu|tớ|mình)\b/.test(textLower);

    const parts = [];
    if (hasAudience) {
      parts.push('Host/Cast addressing audience: "chúng tôi / mình" with "quý vị / mọi người / các bạn"');
    }
    if (hasAnhEm) {
      parts.push('Cast members interacting naturally: "anh / em" and "chị / em"');
    } else if (hasCauTo) {
      parts.push('Cast members interacting as peers: "cậu - tớ" and "mình"');
    }
    if (parts.length === 0) {
      parts.push('Natural reality show dialogue: "anh / em", "chị / em", "mọi người", lively witty banter');
    }
    parts.push('STRICT BAN on romantic couple pronouns ("anh yêu / em yêu") and robotic "tôi / bạn"');

    videoPronounSummary.set(key, parts.join('; '));
  } else if (effectiveGenre === 'casual') {
    const hasMinh = /\b(mình|chúng mình)\b/.test(textLower);
    const hasCacBan = /\b(các bạn|mọi người)\b/.test(textLower);
    const hasTo = /\b(tớ|cậu)\b/.test(textLower);
    const hasAnhEm = /\b(anh|em)\b/.test(textLower);

    let summary = 'Vlogger friendly address: ';
    if (hasMinh && hasCacBan) {
      summary += 'Self is "mình", audience is "các bạn / mọi người". Natural, friendly, conversational tone (NEVER use stiff robotic "tôi / bạn").';
    } else if (hasTo) {
      summary += 'Self is "tớ", audience is "cậu / mọi người". Friendly peer tone.';
    } else if (hasAnhEm) {
      summary += 'Vlogger addresses audience as "các em / mọi người", self is "anh" (or "chị").';
    } else {
      summary += 'Self is "mình", audience is "các bạn / mọi người". Keep warm conversational bond.';
    }
    videoPronounSummary.set(key, summary);
  }
}

/**
 * Sanitize output: Filter profanity and dynamically anchor song perspective
 * Note: Pronoun translation is handled 100% naturally by Gemini AI via prompts
 */
function cleanOutputByGenre(text, effectiveGenre, role, videoTitle = '') {
  if (!text || typeof text !== 'string') return text;
  let cleaned = text;

  // Resolve role from session anchor or artist detection if not explicit
  let effectiveRole = role;
  const key = getVideoAnchorKey(videoTitle);
  if ((!effectiveRole || effectiveRole === 'auto') && videoTitle) {
    if (videoRoleAnchor.has(key)) {
      effectiveRole = videoRoleAnchor.get(key);
    } else {
      const detected = detectFigureGender(videoTitle);
      if (detected) {
        effectiveRole = detected;
        videoRoleAnchor.set(key, detected);
        try { if (chrome.storage && chrome.storage.session) chrome.storage.session.set({ [`role_${key}`]: detected }).catch(() => {}); } catch (_) {}
      }
    }
  }

  // If still auto for lyrics, dynamically deduce and anchor from line content
  if (effectiveGenre === 'lyrics' && (!effectiveRole || effectiveRole === 'auto')) {
    const textLower = cleaned.toLowerCase();
    const femaleMatch = /\b(em yêu anh|em nhớ anh|nhớ anh|yêu anh|bên anh|gần anh|đợi anh|chờ anh|cần anh|vì anh|với anh|của anh|anh ơi|cho em|với em|của em|chính em|bản thân em|em nghĩ|em thấy|em muốn|em biết|em khóc|em mơ|em sợ|em bước|em đau|em chẳng|em không|em đã|em sẽ)\b/.test(textLower);
    const maleMatch = /\b(anh yêu em|anh nhớ em|nhớ em|yêu em|bên em|gần em|đợi em|chờ em|cần em|vì em|với em|của em|em ơi|cho anh|với anh|của anh|chính anh|bản thân anh|anh nghĩ|anh thấy|anh muốn|anh biết|anh khóc|anh mơ|anh sợ|anh bước|anh đau|anh chẳng|anh không|anh đã|anh sẽ)\b/.test(textLower);

    if (femaleMatch && !maleMatch) {
      effectiveRole = 'female';
      if (key) {
        videoRoleAnchor.set(key, 'female');
        try { if (chrome.storage && chrome.storage.session) chrome.storage.session.set({ [`role_${key}`]: 'female' }).catch(() => {}); } catch (_) {}
      }
    } else if (maleMatch && !femaleMatch) {
      effectiveRole = 'male';
      if (key) {
        videoRoleAnchor.set(key, 'male');
        try { if (chrome.storage && chrome.storage.session) chrome.storage.session.set({ [`role_${key}`]: 'male' }).catch(() => {}); } catch (_) {}
      }
    }
  }

  if (effectiveGenre === 'lyrics') {
    // 1. Loại bỏ từ ngữ thô tục, chửi thề, văng tục trong lời bài hát
    cleaned = cleaned
      .replace(/\b(đéo|đếch)\b/gi, 'chẳng')
      .replace(/\b(mẹ kiếp|chó chết|khốn nạn)\b/gi, 'đớn đau thay')
      .replace(/\bchết tiệt\b/gi, 'trời ơi')
      .replace(/\b(đồ khốn|kẻ khốn)\b/gi, 'kẻ vô tâm')
      .replace(/\bvãi\b/gi, 'quá')
      .replace(/\b(vcl|đm|dkm|đụ|lồn|cặc|buồi)\b/gi, '');
  }

  return cleaned;
}

/**
 * Build directive for Vietnamese pronoun roles adaptive to Genre (Music, Reality Shows, News)
 */
function getPronounInstruction(effectiveRole = 'auto', videoTitle = '', effectiveGenre = 'lyrics') {
  const primaryFigure = extractPrimaryFigure(videoTitle);
  const figureHint = primaryFigure ? ` Identified figure/artist: "${primaryFigure}".` : '';

  // 1. REALITY SHOW / TALKSHOW / PODCAST / INTERVIEW DIRECTIVE
  if (effectiveGenre === 'reality_show') {
    const isJpIdolShow = /(乃木坂|櫻坂|日向坂|akb48|ske48|nmb48|hkt48|ngu48|stu48|akbingo|工事中|そこ曲がったら|日向坂で会いましょう|スター誕生|超・乃木坂スター誕生|モニタリング|水曜日のダウンタウン|ロンドンハーツ|アメトーーク|しゃべくり|ジャニーズ|snow man|vs嵐|嵐にしやがれ|バラエティ|月曜から夜ふかし|バナナマン|オードリー)/i.test(videoTitle);

    if (isJpIdolShow) {
      return `\nCRITICAL PRONOUN DIRECTIVE - JAPANESE IDOL VARIETY SHOW (SHOW IDOL NHẬT - 乃木坂工事中, SAKAMICHI, 48G, VARIETY):${figureHint}
- CONTEXT: Japanese idol variety show (such as 乃木坂工事中 / Nogizaka Under Construction, そこ曲がったら、櫻坂?, 日向坂で会いましょう, AKBINGO!, etc.) featuring comedian MCs (Bananaman, Audrey, Sawabe, Tsuchida) interacting with young female idol members.
- IDOL MEMBERS PRONOUNS (XƯNG HÔ CỦA THÀNH VIÊN IDOL):
  * Female idols addressing MCs (Shitara-san, Himura-san, Wakabayashi-san, etc.) or staff: MUST refer to themselves as "em" (e.g. "Em nghĩ là...", "Hôm qua em..."). STRICT PROHIBITION: NEVER use "tôi" for idol members! Address MCs as "anh [Tên]" (e.g. "anh Shitara", "anh Himura", "anh Wakabayashi") or "thầy/chú".
  * Junior idols addressing senior members (Senpai): Junior idols address seniors as "chị [Tên]" (or "tiền bối"), and refer to themselves as "em".
  * Peer members (Dōki - cùng thế hệ): Address each other naturally as "cậu - tớ", "mình - bạn", "mấy đứa mình".
- MCs PRONOUNS (XƯNG HÔ CỦA MC):
  * When addressing idols: MCs address idols as "em", "[Tên]", "mấy đứa", "các em". MCs refer to themselves as "anh", "tôi", or "chúng tôi".
  * When addressing viewers: "quý vị khán giả", "mọi người", "các bạn".
- IDOL ENTERTAINMENT REACTIONS (DỊCH PHẢN ỨNG DỄ THƯƠNG & HÀI HƯỚC):
  * Translate characteristic variety reactions lively and cutely:
    - "えぇー!?" / "嘘!?" -> "Hả?!", "Thật á?!", "Trời ơi!"
    - "ヤバい" -> "Toang rồi!", "Nguy hiểm ghê!", "Ghê thật á!"
    - "可愛い" -> "Dễ thương quá à!", "Đáng yêu xỉu!"
    - "無理無理" -> "Không được đâu!", "Chịu luôn á!"
    - "なんで!?" -> "Sao lại thế chứ?!", "Ủa tại sao?!"
- STRICT PROHIBITION: NEVER use romantic couple pronouns ("anh yêu / em yêu")! This is an idol variety show.`;
    }

    let roleSpecific = '';
    if (effectiveRole === 'show_host') {
      roleSpecific = `\n- SPEAKER IS MC/HOST: When addressing the audience, use "chúng tôi", "quý vị và các bạn", "mọi người". When talking with guests, address them as "bạn", "anh", "chị", "em".`;
    } else if (effectiveRole === 'female') {
      roleSpecific = `\n- SPEAKER IS FEMALE: Address herself naturally as "em" (when talking to seniors/hosts) or "mình/tôi" (sharing views). Address others as "anh", "chị", "bạn".`;
    } else if (effectiveRole === 'male') {
      roleSpecific = `\n- SPEAKER IS MALE: Address himself naturally as "anh" (to juniors) or "em" (to seniors) or "tôi/mình". Address others respectfully.`;
    }

    return `\nCRITICAL PRONOUN DIRECTIVE - REALITY SHOW / TALKSHOW / INTERVIEW (SHOW THỰC TẾ & PHỎNG VẤN):${figureHint}
- CONTEXT: This is a reality show, variety show, podcast, or interview. People are talking and interacting dynamically in real life.
- PRONOUN USAGE (XƯNG HÔ ĐÚNG CHUẨN ĐỜI SỐNG THỰC TẾ):
  * Host with audience: "chúng tôi", "quý vị và các bạn", "mọi người".
  * Participants with each other: Use natural Vietnamese conversational address ("anh / em", "chị / em", "tôi / bạn", "mình / cậu", "mọi người").
  * STRICT PROHIBITION: NEVER use romantic couple pronouns ("anh yêu / em yêu") unless this is explicitly a romantic dating show! This is an entertainment show/interview, NOT a love song.
  * DO NOT use stiff robotic pronouns ("tôi nghĩ bạn nên..."). Translate naturally ("mình nghĩ cậu nên...", "anh thấy em nên...").
  * Translate natural exclamations lively: "Trời ơi!", "Thật không?", "Cười xỉu", "Tuyệt vời!".${roleSpecific}`;
  }

  // 2. NEWS & JOURNALISM DIRECTIVE
  if (effectiveGenre === 'news') {
    return `\nCRITICAL PRONOUN DIRECTIVE - NEWS & JOURNALISM (BÁO CHÍ, THỜI SỰ & PHÓNG SỰ):${figureHint}
- CONTEXT: Formal news report, documentary, or journalistic article.
- PRONOUN USAGE (DANH XƯNG BÁO CHÍ CHUẨN MỰC):
  * News Anchor / Reporter: Use editorial "chúng tôi", "phóng viên", or neutral 3rd-person narration.
  * Public figures & Artists mentioned: MUST be addressed with proper respectful titles:
    - Female artist/singer: "nữ ca sĩ [Tên]", "nữ nghệ sĩ [Tên]", "cô [Tên]"
    - Male artist/singer: "nam ca sĩ [Tên]", "nam diễn viên [Tên]", "anh [Tên]"
    - Experts/Leaders: "ông/bà [Tên]", "vị chuyên gia", "nhà khoa học"
  * STRICT PROHIBITION: NEVER use casual or romantic pronouns ("anh yêu", "em yêu", "cậu ấy", "mình"). Maintain journalistic objectivity and professional distance.
  * Terminology: Use standard, concise journalistic Vietnamese.`;
  }

  // 3. SONG LYRICS DIRECTIVE
  const isJpIdolSong = /(乃木坂|櫻坂|日向坂|akb48|ske48|nmb48|hkt48|ngt48|stu48|=love|≠me|≒joy|坂道|モーニング娘|ももいろクローバー|perfume|ヨルシカ|ずとまよ|ずっと真夜中でいいのに|結束バンド|初音ミク|aimer|yoasobi|zutomayo|yorushika|lisa|reona|ado|j-pop|japanese|anime|vocaloid|chuyên|bài hát nhật)/i.test(videoTitle);

  const jpIdolLyricNotice = isJpIdolSong
    ? `\n- SPECIAL DIRECTIVE FOR JAPANESE IDOL & J-POP MUSIC (NHẠC IDOL NHẬT & J-POP):
  * Maintain the pure, innocent, touching youthfulness (thanh xuân trong sáng, e ấp, tinh khôi) characteristic of Japanese idol music.
  * For Japanese colloquialisms or emotional outbursts like "あんた" (anta), "お前" (omae), "あいつ" (aitsu), "くそ" (kuso), "ちくしょう":
    DO NOT translate literally into aggressive words!
    Translate as delicate, pouting, endearing frustration ("anh", "người ấy", "sao anh lại thế chứ", "đáng ghét thật đấy", "tức thật chứ").
  * ABSOLUTELY NEVER use "tao - mày" or coarse language for Japanese idol lyrics!`
    : '';

  const vulgarBanNotice = `
- ABSOLUTE PROHIBITION ON VULGARITY & RUDE PRONOUNS (TUYỆT ĐỐI CẤM VĂNG TỤC, CẤM "TAO - MÀY"):
  * NEVER use swear words, profanities, or vulgar slang (STRICT BAN on: "đéo", "đếch", "mẹ kiếp", "chết tiệt", "khốn kiếp", "đồ khốn", "vãi", etc.).
  * NEVER use rude/aggressive pronouns "tao - mày", "mày - tao" under any circumstances. Even if the original song has English curses (damn, bitch, shit, fuck) or Japanese slang, adapt them poetically into natural lyrical emotion (pain, regret, heartbreak, sweet pouting), NOT vulgarity.
- ROMANTIC EMOTIONALITY ("TÌNH", GIÀU CHẤT THƠ, TỰ NHIÊN NHƯ NGƯỜI DỊCH):
  * Song lyrics must sound poetic, melodic, deeply emotional, and authentic ("tình", êm dịu, da diết).
  * Translate like a skilled human music lyricist: flowing cadence, emotional resonance, rich romantic tone. For love songs, make it genuinely sweet, intimate, or touching.`;

  if (effectiveRole === 'female') {
    return `\nCRITICAL PRONOUN DIRECTIVE - FEMALE SINGER / IDOL (ĐỒNG NHẤT 100% NGÔI XƯNG NỮ HÁT & GIÀU CẢM XÚC):${vulgarBanNotice}${jpIdolLyricNotice}
- SINGER IS FEMALE: You MUST maintain an absolute, 100% consistent "Em - Anh" lyrical voice across EVERY SINGLE LINE of the song.
- 1st-person pronouns ("I", "me", "my", "mine", "myself", "watashi", "boku", "atashi") MUST ALWAYS be translated as "em" in every line.
  * STRICT BAN: NEVER use "tôi", NEVER use "mình", NEVER use "tớ", NEVER use "tao", NEVER use "anh" for the female singer anywhere in the song!
  * Even in descriptive or reflective lines (e.g. "I walk alone in the rain"), translate "I" as "em" ("Em bước một mình dưới mưa").
- 2nd-person pronouns ("you", "your", "yours", "anata", "kimi", "anta", "omae") MUST ALWAYS be translated as "anh" (or "người" if poetic).
  * STRICT BAN: NEVER translate "you" as "cậu", NEVER as "mày", NEVER as "bạn"!
- DO NOT MIX PRONOUNS: Singer remains "em" and the loved one remains "anh" from the first line to the very last line!`;
  }

  if (effectiveRole === 'male') {
    return `\nCRITICAL PRONOUN DIRECTIVE - MALE SINGER (ĐỒNG NHẤT 100% NGÔI XƯNG NAM HÁT & GIÀU CẢM XÚC):${vulgarBanNotice}
- SINGER IS MALE: You MUST maintain an absolute, 100% consistent "Anh - Em" lyrical voice across EVERY SINGLE LINE of the song.
- 1st-person pronouns ("I", "me", "my", "mine", "myself", "boku", "ore") MUST ALWAYS be translated as "anh" in every line.
  * STRICT BAN: NEVER use "tôi", NEVER use "mình", NEVER use "tớ", NEVER use "tao", NEVER use "em" for the male singer anywhere in the song!
  * Even in descriptive or reflective lines, translate "I" as "anh" ("Anh bước một mình dưới mưa").
- 2nd-person pronouns ("you", "your", "yours", "kimi", "omae") MUST ALWAYS be translated as "em" (or "người" if poetic).
  * STRICT BAN: NEVER translate "you" as "cậu", NEVER as "mày", NEVER as "bạn"!
- DO NOT MIX PRONOUNS: Singer remains "anh" and the loved one remains "em" from the first line to the very last line!`;
  }

  if (effectiveRole === 'neutral') {
    return `\nCRITICAL PRONOUN DIRECTIVE - NEUTRAL / REFLECTIVE LYRICS:${vulgarBanNotice}
- Maintain an absolute, 100% consistent "Tôi - Bạn" or "Ta - Người" perspective across all lines.
- 1st-person pronouns ("I", "me", "my") MUST ALWAYS be translated as "tôi" (or "ta") in every line.
  * STRICT BAN: NEVER use "tao", NEVER use "anh", NEVER use "em" for the singer anywhere in the song!
- 2nd-person pronouns ("you", "your") MUST ALWAYS be translated as "bạn" or "người" (NEVER "mày").
- DO NOT MIX PRONOUNS across lines!`;
  }

  // Default: 'auto' with mandatory artist & performer identification
  const parsedArtist = primaryFigure;
  const artistLookupHint = parsedArtist
    ? `\n- ARTIST IDENTIFICATION: The performer is identified as "${parsedArtist}". Look up your knowledge base to determine whether "${parsedArtist}" is female, male, or a band.`
    : `\n- ARTIST / CONTEXT IDENTIFICATION: Inspect the Video Metadata / Title to identify the performing artist and their gender/persona.`;

  return `\nCRITICAL PRONOUN DIRECTIVE - SONG LYRICS (QUY TẮC DỊCH NHẠC GIÀU CẢM XÚC & BẢO VỆ NGÔI XƯNG):${vulgarBanNotice}${jpIdolLyricNotice}${artistLookupHint}
- Determine the singer's gender/perspective from the artist name or song title BEFORE translating:
  * Female singer/idol: Singer is ALWAYS "em" (self), listener/beloved is ALWAYS "anh" (or "người"). BAN: "tôi", "tớ", "cậu", "tao", "mày"!
  * Male singer: Singer is ALWAYS "anh" (self), listener/beloved is ALWAYS "em" (or "người"). BAN: "tôi", "tớ", "cậu", "tao", "mày"!
  * Band, duet, or philosophical song: Singer is "tôi" (hoặc "ta"), listener is "bạn" hoặc "người" (hoặc "anh - em" nếu là tình ca).
- ABSOLUTE PROHIBITION ON MIXING PRONOUNS: Stick to ONE SINGLE lyrical perspective 100% consistently across EVERY SINGLE LINE of the song. Do not flip between "tôi", "em", "anh", or "tớ"!`;
}

/**
 * Construct adaptive prompt based on video genre, title, entities and lyrics detection
 */
function buildGeminiSubtitlePrompt(text, targetName, videoTitle = '', style = 'auto', pronounRole = 'auto', contextTail = []) {
  const contextLine = videoTitle ? `Video Context / Metadata: "${videoTitle.slice(0, 240)}"\n` : '';
  const effectiveGenre = resolveEffectiveGenre(style, videoTitle);
  let styleInstruction = '';

  if (effectiveGenre === 'lyrics') {
    const isJpSong = /(乃木坂|櫻坂|日向坂|akb48|坂道|aimer|yoasobi|zutomayo|yorushika|lisa|reona|ado|j-pop|japanese|anime|vocaloid|chuyên|bài hát nhật)/i.test(videoTitle);
    const jpSpecific = isJpSong
      ? ` SPECIAL NOTE FOR JAPANESE IDOL & J-POP: Capture the pure, youthful, gentle romance (thanh xuân trong sáng, ngọt ngào, giàu chất thơ). ABSOLUTE BAN on vulgar words, swearing, or rude pronouns (tao - mày).`
      : '';
    styleInstruction = `MODE: SONG LYRICS. Translate with deep emotion, lyrical grace, and poetic romance like an experienced Vietnamese lyricist (phổ lời Việt mượt mà, da diết, tình cảm, sâu lắng, đậm chất thơ; các bài tình cảm phải thật 'tình'; tuyệt đối không dịch khô cứng máy móc, không văng tục thô lỗ hay xưng hô tao mày). Preserve musical notes (♪, ♫) if present.${jpSpecific}`;
  } else if (effectiveGenre === 'reality_show') {
    styleInstruction = `MODE: REALITY SHOW & TALK SHOW. Translate lively, authentic, witty, and conversational Vietnamese for reality/game show dialogue.`;
  } else if (effectiveGenre === 'news') {
    styleInstruction = `MODE: NEWS & ARTICLES. Use formal, professional, objective, journalistic Vietnamese with accurate terminology and proper respectful titles.`;
  } else {
    styleInstruction = `MODE: CASUAL CONVERSATION & VLOGS. Use natural, lively, colloquial Vietnamese dialogue.`;
  }

  const effectiveRole = resolveSongPronounRole(pronounRole, videoTitle, effectiveGenre);
  const pronounInstruction = targetName === 'Vietnamese' ? getPronounInstruction(effectiveRole, videoTitle, effectiveGenre) : '';

  let previousContextSection = '';
  if (Array.isArray(contextTail) && contextTail.length > 0) {
    const validTails = contextTail.filter((t) => t && t.original && t.translation);
    if (validTails.length > 0) {
      const tailFormatted = validTails
        .map((t) => `- Earlier Line: "${t.original}" -> Translated: "${t.translation}"`)
        .join('\n');
      previousContextSection = `\nPREVIOUS TRANSLATED CONTEXT (NGỮ CẢNH ĐÃ DỊCH TRƯỚC ĐÓ - DÙNG ĐỂ NỐI MẠCH VĂN):
The following line(s) were translated immediately prior to this line. Use them to maintain seamless narrative flow, poetic romance, lyrical continuity, and consistent pronouns:
${tailFormatted}
MANDATORY DIRECTIVE: Output translation ONLY for the line below. Connect pronouns and emotional tone seamlessly with the previous context!\n`;
    }
  }

  return `You are a world-class bilingual subtitle translator and localization expert adapting style to video genre:
${contextLine}${styleInstruction}${pronounInstruction}${previousContextSection}

Translate directly into natural, concise ${targetName} suitable for video subtitles. Output ONLY the translated text, no quotes, no explanations:
${text}`;
}

function buildGeminiBatchSubtitlePrompt(lines, targetName, videoTitle = '', style = 'auto', pronounRole = 'auto', contextTail = []) {
  const contextLine = videoTitle ? `Video Context / Metadata: "${videoTitle.slice(0, 240)}"\n` : '';
  const effectiveGenre = resolveEffectiveGenre(style, videoTitle);
  const promptLines = lines.map((text, idx) => `${idx + 1}. ${text}`).join('\n');
  let styleInstruction = '';

  if (effectiveGenre === 'lyrics') {
    const isJpSong = /(乃木坂|櫻坂|日向坂|akb48|坂道|aimer|yoasobi|zutomayo|yorushika|lisa|reona|ado|j-pop|japanese|anime|vocaloid|chuyên|bài hát nhật)/i.test(videoTitle);
    const jpSpecific = isJpSong
      ? ` SPECIAL NOTE FOR JAPANESE IDOL & J-POP: Deliver pure, youthful, touching lyrical romance (thanh xuân trong sáng, e ấp, ngọt ngào). ABSOLUTE BAN on vulgar words or rude 'tao - mày' pronouns.`
      : '';
    styleInstruction = `MODE: SONG LYRICS. Translate these continuous lines with emotional depth, poetic cadence, and romantic warmth (phổ lời bài hát tình cảm, mượt mà, sâu lắng, có hồn như người dịch; các bài tình yêu phải thật 'tình' và êm dịu; tuyệt đối cấm lời thô tục hay vai vế 'tao mày'). Preserve musical notes (♪, ♫) if present.${jpSpecific}`;
  } else if (effectiveGenre === 'reality_show') {
    styleInstruction = `MODE: REALITY SHOW & TALK SHOW. Translate these continuous dialogue lines as authentic, witty, lively conversation for variety/reality show.`;
  } else if (effectiveGenre === 'news') {
    styleInstruction = `MODE: NEWS & ARTICLES. Use formal, professional, objective, journalistic Vietnamese with accurate terminology and proper public figure titles.`;
  } else {
    styleInstruction = `MODE: CASUAL & VLOGS. Use lively, natural, colloquial Vietnamese dialogue.`;
  }

  const effectiveRole = resolveSongPronounRole(pronounRole, videoTitle, effectiveGenre);
  const pronounInstruction = targetName === 'Vietnamese' ? getPronounInstruction(effectiveRole, videoTitle, effectiveGenre) : '';

  let summarySection = '';
  if (effectiveGenre === 'reality_show' || effectiveGenre === 'casual') {
    const key = getVideoAnchorKey(videoTitle);
    const establishedSummary = videoPronounSummary.get(key);
    if (establishedSummary) {
      summarySection = `\nESTABLISHED PRONOUN & RELATIONSHIP SUMMARY (TÓM TẮT XƯNG HÔ ĐÃ THIẾT LẬP TỪ BATCH TRƯỚC):
- Relationship Mapping: ${establishedSummary}
- CRITICAL REQUIREMENT: Maintain this EXACT conversational relationship and pronoun mapping consistently across all lines below!\n`;
    }
  }

  let previousContextSection = '';
  if (Array.isArray(contextTail) && contextTail.length > 0) {
    const validTails = contextTail.filter((t) => t && t.original && t.translation);
    if (validTails.length > 0) {
      const tailFormatted = validTails
        .map((t) => `- Earlier Line: "${t.original}" -> Translated: "${t.translation}"`)
        .join('\n');
      previousContextSection = `\nPREVIOUS TRANSLATED CONTEXT (NGỮ CẢNH ĐÃ DỊCH TRƯỚC ĐÓ - DÙNG ĐỂ NỐI MẠCH VĂN):
The following line(s) were translated immediately prior to this batch. Use them to maintain seamless narrative flow, poetic rhyme, lyrical continuity, and consistent pronouns:
${tailFormatted}
MANDATORY DIRECTIVE: DO NOT re-translate the previous lines above! Output translations ONLY for the numbered lines below (1 to ${lines.length}). Connect pronouns and emotional tone seamlessly with the previous context!\n`;
    }
  }

  return `You are a world-class bilingual subtitle translator translating continuous video subtitles:
${contextLine}${styleInstruction}${pronounInstruction}${summarySection}${previousContextSection}
Maintain exact line numbering (e.g. "1. <translation>"). Output ONLY the numbered translated lines in ${targetName}. Do NOT include explanations, previous lines, or metadata:
${promptLines}`;
}

let geminiKeyIndex = 0;

/**
 * Parse and clean multi-key pool (comma, semicolon, or newline separated)
 */
function getGeminiApiKeys(rawKey) {
  if (!rawKey || typeof rawKey !== 'string') return [];
  return rawKey
    .split(/[\n,;]+/)
    .map((k) => k.trim())
    .filter((k) => k.length > 10);
}

/**
 * Get next rotating Gemini API key
 */
function getNextGeminiApiKey(rawKey) {
  const keys = getGeminiApiKeys(rawKey);
  if (keys.length === 0) return rawKey ? rawKey.trim() : '';
  const key = keys[geminiKeyIndex % keys.length];
  geminiKeyIndex = (geminiKeyIndex + 1) % keys.length;
  return key;
}

/**
 * Return current date in Pacific Time (America/Los_Angeles) matching Google AI Studio reset
 */
function getQuotaDateKey() {
  try {
    return new Date().toLocaleDateString('en-CA', { timeZone: 'America/Los_Angeles' });
  } catch (_) {
    return new Date().toISOString().slice(0, 10);
  }
}

/**
 * Return stable identifier for API key(s) to track quota per key
 */
function getApiKeyHash(rawKey) {
  if (!rawKey) return 'default';
  const keys = getGeminiApiKeys(rawKey);
  if (keys.length === 0) return 'default';
  return keys.map((k) => k.slice(-8)).sort().join('_');
}

/**
 * Record quota usage in chrome.storage.local (Both per-key and global)
 */
async function recordGeminiQuotaUsage(linesCount = 1, rawKey = '') {
  try {
    const today = getQuotaDateKey(); // Pacific Time 'YYYY-MM-DD'
    const keyHash = getApiKeyHash(rawKey);
    const keyUsageKey = `gemini_req_${keyHash}_${today}`;

    const data = await chrome.storage.local.get([
      keyUsageKey,
      'gemini_requests_today',
      'gemini_requests_date',
      'gemini_cues_translated',
      'gemini_quota_saved',
    ]);

    let keyRequestsToday = data[keyUsageKey] || 0;
    keyRequestsToday += 1;

    let requestsToday = data.gemini_requests_today || 0;
    if (data.gemini_requests_date !== today) {
      requestsToday = 0; // Reset for new day
    }
    requestsToday += 1;

    const cuesTranslated = (data.gemini_cues_translated || 0) + linesCount;

    await chrome.storage.local.set({
      [keyUsageKey]: keyRequestsToday,
      gemini_requests_today: requestsToday,
      gemini_requests_date: today,
      gemini_cues_translated: cuesTranslated,
    });
  } catch (_) {}
}

/**
 * Record quota saved by offline noise filters & caching
 */
async function recordQuotaSaved(count = 1) {
  try {
    const data = await chrome.storage.local.get(['gemini_quota_saved']);
    await chrome.storage.local.set({
      gemini_quota_saved: (data.gemini_quota_saved || 0) + count,
    });
  } catch (_) {}
}

/**
 * Call Gemini API with automatic transparent fallback across candidate models
 * Keeps gemini-3.5-flash-lite prioritized, but if 404, gracefully switches to available models
 */
async function callGeminiApiWithFallback(apiKey, prompt, generationConfig, requestedModel = 'gemini-3.5-flash-lite') {
  const chosenModel = resolveGeminiModel(requestedModel);
  const candidateList = [];
  if (activeWorkingGeminiModel && !candidateList.includes(activeWorkingGeminiModel)) {
    candidateList.push(activeWorkingGeminiModel);
  }
  if (chosenModel && !candidateList.includes(chosenModel)) {
    candidateList.push(chosenModel);
  }
  GEMINI_CANDIDATE_MODELS.forEach((m) => {
    if (!candidateList.includes(m)) candidateList.push(m);
  });

  let lastError = null;
  for (const modelName of candidateList) {
    try {
      const url = `https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(modelName)}:generateContent?key=${encodeURIComponent(apiKey)}`;
      const res = await fetch(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contents: [{ parts: [{ text: prompt }] }],
          generationConfig: generationConfig
        }),
        keepalive: true
      });

      if (res.status === 404) {
        console.warn(`[YT Sub Translate] Gemini model ${modelName} returned 404, falling back to next candidate...`);
        lastError = new Error(`HTTP 404 for ${modelName}`);
        continue;
      }

      if (!res.ok) {
        let errMessage = `HTTP ${res.status}`;
        try {
          const errJson = await res.json();
          if (errJson?.error?.message) errMessage = errJson.error.message;
        } catch (_) {}
        if (res.status === 400 && (errMessage.includes('not found') || errMessage.includes('not supported'))) {
          console.warn(`[YT Sub Translate] Gemini model ${modelName} not supported (${errMessage}), trying next candidate...`);
          lastError = new Error(errMessage);
          continue;
        }
        throw new Error(`Gemini API (${modelName}): ${errMessage}`);
      }

      activeWorkingGeminiModel = modelName;
      return { res, modelName };
    } catch (err) {
      if (err.message && (err.message.includes('404') || err.message.includes('not supported') || err.message.includes('not found'))) {
        lastError = err;
        continue;
      }
      throw err;
    }
  }

  throw lastError || new Error('All candidate Gemini models failed');
}

/**
 * Translate single subtitle line using Google Gemini AI API (Fast, low-latency, genre-aware)
 */
async function translateWithGemini(text, sourceLang, targetLang, apiKey, model = 'gemini-3.5-flash-lite', videoTitle = '', style = 'auto', pronounRole = 'auto', contextTail = []) {
  const effectiveKey = getNextGeminiApiKey(apiKey);
  if (!effectiveKey) {
    throw new Error('Missing Gemini API Key');
  }
  recordGeminiQuotaUsage(1, effectiveKey);

  const tl = targetLang || 'vi';
  const targetName = tl === 'vi' ? 'Vietnamese' : tl;
  const chosenModel = resolveGeminiModel(model);
  const effectiveGenre = resolveEffectiveGenre(style, videoTitle);
  const effectiveRole = resolveSongPronounRole(pronounRole, videoTitle, effectiveGenre);

  const prompt = buildGeminiSubtitlePrompt(text, targetName, videoTitle, style, effectiveRole, contextTail);

  const { res, modelName: actualModel } = await callGeminiApiWithFallback(
    effectiveKey,
    prompt,
    {
      temperature: effectiveGenre === 'news' ? 0.15 : 0.35,
      maxOutputTokens: 120
    },
    chosenModel
  );

  const data = await res.json();
  const rawText = data?.candidates?.[0]?.content?.parts?.[0]?.text;
  if (rawText && typeof rawText === 'string') {
    let cleaned = rawText
      .trim()
      .replace(/^["'“”«»]+|["'“”«»]+$/g, '')
      .replace(/^(Bản dịch|Translation):\s*/i, '')
      .trim();
    if (cleaned) {
      if (effectiveGenre === 'lyrics') {
        anchorRoleFromTranslation(videoTitle, cleaned);
      }
      const finalRole = resolveSongPronounRole(pronounRole, videoTitle, effectiveGenre);
      cleaned = cleanOutputByGenre(decodeHtmlEntities(cleaned), effectiveGenre, finalRole, videoTitle);
      return cleaned;
    }
  }

  throw new Error(`Invalid response structure from Gemini API (${actualModel})`);
}

/**
 * Batch translate multiple subtitle lines in a single Gemini API call (High throughput, 0ms playback, genre-aware)
 */
async function translateBatchWithGemini(lines, sourceLang, targetLang, apiKey, model = 'gemini-3.5-flash-lite', videoTitle = '', style = 'auto', pronounRole = 'auto', contextTail = []) {
  if (!lines || lines.length === 0) return [];
  const effectiveKey = getNextGeminiApiKey(apiKey);
  if (!effectiveKey) throw new Error('Missing Gemini API Key');
  recordGeminiQuotaUsage(lines.length, effectiveKey);

  const tl = targetLang || 'vi';
  const targetName = tl === 'vi' ? 'Vietnamese' : tl;
  const chosenModel = resolveGeminiModel(model);
  const effectiveGenre = resolveEffectiveGenre(style, videoTitle);
  const effectiveRole = resolveSongPronounRole(pronounRole, videoTitle, effectiveGenre);

  const prompt = buildGeminiBatchSubtitlePrompt(lines, targetName, videoTitle, style, effectiveRole, contextTail);

  const { res, modelName: actualModel } = await callGeminiApiWithFallback(
    effectiveKey,
    prompt,
    {
      temperature: effectiveGenre === 'news' ? 0.15 : 0.35,
      maxOutputTokens: 2200
    },
    chosenModel
  );

  const data = await res.json();
  const rawText = data?.candidates?.[0]?.content?.parts?.[0]?.text || '';

  const rawResults = new Array(lines.length).fill('');
  const outputLines = rawText.split('\n');
  for (const line of outputLines) {
    const match = line.match(/^\s*(\d+)[\.\:\)]\s*(.*)$/);
    if (match) {
      const idx = parseInt(match[1], 10) - 1;
      if (idx >= 0 && idx < lines.length) {
        rawResults[idx] = decodeHtmlEntities(match[2].trim());
      }
    }
  }

  // Fallback if numbered format failed
  if (rawResults.filter(Boolean).length < lines.length / 2) {
    const cleanLines = outputLines
      .map(l => l.replace(/^\s*\d+[\.\:\)]\s*/, '').trim())
      .filter(Boolean);
    if (cleanLines.length === lines.length) {
      for (let i = 0; i < lines.length; i++) {
        rawResults[i] = decodeHtmlEntities(cleanLines[i]);
      }
    }
  }

  // Anchor role from full batch first so all lines are unified
  if (effectiveGenre === 'lyrics' && rawResults.some(Boolean)) {
    anchorRoleFromTranslation(videoTitle, rawResults.join(' '));
  }

  // Update pronoun & relationship summary for reality shows and vlogs
  if ((effectiveGenre === 'reality_show' || effectiveGenre === 'casual') && rawResults.some(Boolean)) {
    updatePronounSummaryFromTranslation(videoTitle, rawResults.join(' '), effectiveGenre);
  }

  // Re-resolve effectiveRole with freshly anchored perspective so all batch lines are unified!
  const finalRole = resolveSongPronounRole(pronounRole, videoTitle, effectiveGenre);

  // Sanitize every line with videoTitle and the anchored role
  const results = rawResults.map((line) => {
    return line ? cleanOutputByGenre(line, effectiveGenre, finalRole, videoTitle) : '';
  });

  return results;
}

/**
 * Handle translation requests with caching and multi-engine routing
 */
async function handleTranslation({ text, sourceLang = 'auto', targetLang = 'vi', service = 'google', apiKey = '', model = 'gemini-3.5-flash-lite', videoTitle = '', style = 'auto', pronounRole = 'auto', isAutoTranslate = false, isAutoGenerated = false, bypassGemini = false, contextTail = [] }) {
  const trimmed = (text || '').trim();
  if (!trimmed) {
    return { success: true, translation: '' };
  }

  const anchorKey = service === 'gemini' ? `:${getVideoAnchorKey(videoTitle)}` : '';
  const cacheKey = `${service}:${style || 'auto'}:${pronounRole || 'auto'}${anchorKey}:${sourceLang}->${targetLang}:${apiKey ? 'custom' : 'free'}:${trimmed}`;

  // Check in-memory cache
  if (translationCache.has(cacheKey)) {
    return {
      success: true,
      translation: translationCache.get(cacheKey),
      fromCache: true,
    };
  }

  try {
    let translated = '';

    if (service === 'gemini') {
      const gKey = (apiKey || '').trim();
      // If YouTube auto-translate or ASR auto-generated caption is active, do not call Gemini to avoid request spam & save user quota
      if (isAutoTranslate || isAutoGenerated || bypassGemini) {
        translated = await translateWithFreeGoogleEndpoint(trimmed, sourceLang, targetLang);
        recordQuotaSaved(1);
      } else if (gKey) {
        try {
          translated = await translateWithGemini(trimmed, sourceLang, targetLang, gKey, model, videoTitle, style, pronounRole, contextTail);
        } catch (err) {
          console.warn('[YT Sub Translate] Gemini API failed, falling back to Google Translate...', err);
          translated = await translateWithFreeGoogleEndpoint(trimmed, sourceLang, targetLang);
        }
      } else {
        translated = await translateWithFreeGoogleEndpoint(trimmed, sourceLang, targetLang);
      }
    } else if (apiKey && apiKey.trim().length > 0) {
      translated = await translateWithGoogleCloudApi(trimmed, sourceLang, targetLang, apiKey.trim());
    } else if (service === 'mymemory') {
      try {
        translated = await translateWithMyMemory(trimmed, sourceLang, targetLang);
      } catch (err) {
        console.warn('[YT Sub Translate] MyMemory failed, falling back to Google Translate...', err);
        translated = await translateWithFreeGoogleEndpoint(trimmed, sourceLang, targetLang);
      }
    } else {
      // Default: Google Translate fast endpoints
      translated = await translateWithFreeGoogleEndpoint(trimmed, sourceLang, targetLang);
    }

    // Enforce genre and pronoun sanitization across all engine outputs (Google, MyMemory, Gemini)
    if (translated) {
      const effectiveGenre = resolveEffectiveGenre(style, videoTitle);
      if (effectiveGenre === 'lyrics') {
        anchorRoleFromTranslation(videoTitle, translated);
      }
      const finalRole = resolveSongPronounRole(pronounRole, videoTitle, effectiveGenre);
      translated = cleanOutputByGenre(translated, effectiveGenre, finalRole, videoTitle);
    }

    // Add to cache with size limit check
    if (translationCache.size >= MAX_CACHE_SIZE) {
      const firstKey = translationCache.keys().next().value;
      translationCache.delete(firstKey);
    }
    translationCache.set(cacheKey, translated);

    return {
      success: true,
      translation: translated,
      fromCache: false,
    };
  } catch (error) {
    console.error('[YT Sub Translate] Translation error:', error);
    return {
      success: false,
      error: error.message || 'Translation failed',
    };
  }
}

// Handle message communication from content script or popup
chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  if (request.action === 'TRANSLATE') {
    handleTranslation(request)
      .then((res) => sendResponse(res))
      .catch((err) => sendResponse({ success: false, error: err.message }));
    return true;
  }

  if (request.action === 'CLEAR_CACHE') {
    translationCache.clear();
    videoRoleAnchor.clear();
    try {
      if (chrome.storage && chrome.storage.session) {
        chrome.storage.session.clear().catch(() => {});
      }
    } catch (_) {}
    chrome.tabs.query({ url: '*://*.youtube.com/*' }, (tabs) => {
      if (tabs && tabs.length > 0) {
        tabs.forEach((tab) => {
          chrome.tabs.sendMessage(tab.id, { action: 'CLEAR_LOCAL_CACHE' }).catch(() => {});
        });
      }
    });
    sendResponse({ success: true, count: 0 });
    return true;
  }

  if (request.action === 'GET_CACHE_STATS') {
    sendResponse({ success: true, size: translationCache.size });
    return true;
  }

  if (request.action === 'TRANSLATE_BATCH_GEMINI') {
    if (request.isAutoTranslate || request.isAutoGenerated || request.bypassGemini) {
      sendResponse({ success: true, translations: [] });
      return true;
    }
    translateBatchWithGemini(
      request.lines,
      request.sourceLang || 'auto',
      request.targetLang || 'vi',
      request.apiKey,
      request.model || 'gemini-3.5-flash-lite',
      request.videoTitle || '',
      request.style || 'auto',
      request.pronounRole || 'auto',
      request.contextTail || []
    )
      .then((translations) => sendResponse({ success: true, translations }))
      .catch((err) => sendResponse({ success: false, error: err.message }));
    return true;
  }

  if (request.action === 'TEST_GEMINI_KEY') {
    const chosenModel = resolveGeminiModel(request.model || 'gemini-3.5-flash-lite');
    translateWithGemini(
      '♪ Cause baby now we got bad blood, you know it used to be mad love ♪',
      'en',
      'vi',
      request.apiKey,
      chosenModel,
      'Taylor Swift - Bad Blood (Official Music Video) | Artist: Taylor Swift',
      request.style || 'auto',
      request.pronounRole || 'auto'
    )
      .then((trans) => sendResponse({ success: true, translation: trans, model: chosenModel }))
      .catch((err) => sendResponse({ success: false, error: err.message }));
    return true;
  }

  if (request.action === 'RECORD_QUOTA_SAVED') {
    recordQuotaSaved(request.count || 1);
    sendResponse({ success: true });
    return true;
  }

  if (request.action === 'CHECK_GEMINI_QUOTA') {
    (async () => {
      const startTime = Date.now();
      const rawKey = request.apiKey || '';
      const keys = getGeminiApiKeys(rawKey);
      const testKey = keys.length > 0 ? keys[0] : rawKey.trim();

      if (!testKey) {
        sendResponse({ success: false, error: 'Chưa cấu hình Gemini API Key' });
        return;
      }

      const today = getQuotaDateKey();
      const keyHash = getApiKeyHash(rawKey);
      const keyUsageKey = `gemini_req_${keyHash}_${today}`;
      const stats = await chrome.storage.local.get([
        keyUsageKey,
        'gemini_requests_today',
        'gemini_requests_date',
        'gemini_cues_translated',
        'gemini_quota_saved'
      ]);

      let requestsToday = stats[keyUsageKey];
      if (typeof requestsToday !== 'number') {
        requestsToday = (stats.gemini_requests_date === today) ? (stats.gemini_requests_today || 0) : 0;
      }

      try {
        const chosenModel = resolveGeminiModel(request.model || 'gemini-3.5-flash-lite');
        const url = `https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(chosenModel)}:generateContent?key=${encodeURIComponent(testKey)}`;
        const res = await fetch(url, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            contents: [{ parts: [{ text: 'Hello' }] }],
            generationConfig: { maxOutputTokens: 5 }
          })
        });

        const latency = Date.now() - startTime;

        const syncSettings = await chrome.storage.sync.get(['geminiRpdLimit']);
        const baseRpd = syncSettings.geminiRpdLimit || 500;
        const keyCount = keys.length || 1;
        const maxRpd = keyCount * baseRpd;
        const maxRpm = keyCount * 15;

        if (res.ok) {
          sendResponse({
            success: true,
            status: 'active',
            latencyMs: latency,
            requestsToday,
            cuesTranslated: stats.gemini_cues_translated || 0,
            quotaSaved: stats.gemini_quota_saved || 0,
            keyCount,
            maxRpd,
            maxRpm,
            message: `Key hoạt động tốt • Ping: ${latency}ms • Quota sẵn sàng`
          });
        } else if (res.status === 429) {
          sendResponse({
            success: true,
            status: 'rate_limited',
            latencyMs: latency,
            requestsToday,
            cuesTranslated: stats.gemini_cues_translated || 0,
            quotaSaved: stats.gemini_quota_saved || 0,
            keyCount,
            maxRpd,
            maxRpm,
            message: 'Tạm thời chạm giới hạn 15 RPM • Vui lòng đợi 30s hoặc thêm key phụ'
          });
        } else {
          let errText = `HTTP ${res.status}`;
          try {
            const errJson = await res.json();
            if (errJson?.error?.message) errText = errJson.error.message;
          } catch (_) {}
          sendResponse({
            success: false,
            status: 'error',
            error: errText,
            requestsToday,
            cuesTranslated: stats.gemini_cues_translated || 0,
            quotaSaved: stats.gemini_quota_saved || 0,
            keyCount: keys.length || 1
          });
        }
      } catch (err) {
        sendResponse({
          success: false,
          status: 'network_error',
          error: err.message,
          requestsToday,
          cuesTranslated: stats.gemini_cues_translated || 0,
          quotaSaved: stats.gemini_quota_saved || 0,
          keyCount: keys.length || 1
        });
      }
    })();
    return true;
  }

  if (request.action === 'PING') {
    sendResponse({ success: true, pong: true });
    return true;
  }
});
