/**
 * YouTube Subtitle Translator - Content Script (High Performance Multi-Engine)
 * Features:
 * - Authentic YouTube native subtitle styling (unified caption-window)
 * - Atomic simultaneous display: original and translated lines appear at the exact same instant
 * - Multi-engine support: YouTube Native Subtitles (&tlang=), Google Translate, MyMemory Translated
 * - High-speed Keep-Alive direct fetch with AbortController
 */

(() => {
  'use strict';

  // Current extension settings
  let settings = {
    enabled: true,
    displayMode: 'bilingual', // 'bilingual' | 'vietnamese_only' | 'off'
    translationService: 'google', // 'google' | 'youtube' | 'mymemory' | 'google_cloud'
    sourceLang: 'auto',
    targetLang: 'vi',
    fontSize: 20,
    fullscreenOptimize: true, // Auto-scale subtitle size in fullscreen mode
    fullscreenScaleMode: 'sync_yt', // 'sync_yt' | '1.25' | '1.4' | '1.5' | '1.75' | '2.0' | 'custom'
    fullscreenCustomSize: 32, // Custom font size when mode is 'custom'
    fontColor: '#FFFFFF',
    originalColor: '#FFFFFF',
    bgOpacity: 75,
    subPosition: 'bottom',
    subBottomOffset: 0, // 0 = automatic responsive elevation above player controls
    hideOriginalNative: true,
    customApiKey: '',
    geminiApiKey: '',
    geminiModel: 'gemini-3.5-flash-lite',
    geminiStyle: 'auto', // 'auto' | 'lyrics' | 'news' | 'casual'
    geminiPronounRole: 'auto', // 'auto' | 'female' | 'male' | 'neutral'
  };

  // Local synchronous in-memory cache for 0ms lookup
  const localCache = new Map();
  const MAX_LOCAL_CACHE = 5000;

  // Active translation controller and in-flight request deduplication
  let activeAbortController = null;
  const inFlightTranslations = new Map();

  // State variables
  let playerElement = null;
  let captionObserver = null;
  let lastCaptionText = '';
  let overlayContainer = null;
  let innerBox = null;
  let origWrapper = null;
  let transWrapper = null;
  let originalTextElement = null;
  let translatedTextElement = null;
  let isDragging = false;
  let startY = 0;
  let pretranslateQueue = [];
  let isPretranslating = false;
  let detectedCaptionLang = '';
  let isYouTubeAutoTranslateActive = false;
  let isAutoGeneratedTrack = false;
  let nativeTranslationsByMs = new Map(); // startMs -> transText
  let nativeTranslationsByText = new Map(); // origText -> transText
  let videoTimedCues = []; // Chronological list of { startMs, durMs, text }
  let attachedVideoElement = null;
  let lastTranslatedTail = []; // Rolling context tail: [{ original, translation }] to connect subsequent batches
  let currentSongPronounRole = 'auto'; // 'auto' | 'female' | 'male' - Session-locked song pronoun perspective

  /**
   * Intelligently select preceding cues containing personal pronouns for seamless context flow
   */
  function getSmartContextTail(tailList = [], maxItems = 2) {
    if (!Array.isArray(tailList) || tailList.length === 0) return [];
    const valid = tailList.filter((t) => t && t.original && t.translation && t.translation.trim().length > 3);
    if (valid.length === 0) return [];

    const pronounRegex = /\b(em|anh|tôi|mình|tớ|cậu|bạn|chúng ta|đôi ta)\b/i;
    const withPronouns = valid.filter((t) => pronounRegex.test(t.translation));
    if (withPronouns.length > 0) {
      return withPronouns.slice(-maxItems);
    }
    return valid.slice(-maxItems);
  }

  /**
   * Automatically detect and anchor song pronoun role upon first translated cue/batch
   */
  function updateSongPronounRoleFromTranslations(translations) {
    if (currentSongPronounRole !== 'auto') return;
    const combined = (Array.isArray(translations) ? translations.join(' ') : (translations || '')).toLowerCase();
    const femaleSignals = (combined.match(/\b(em yêu anh|em nhớ anh|nhớ anh|yêu anh|bên anh|gần anh|đợi anh|chờ anh|cần anh|vì anh|với anh|của anh|anh ơi|cho em|với em|của em|chính em|bản thân em|em nghĩ|em thấy|em muốn|em biết|em khóc|em mơ|em sợ|em bước|em đau|em chẳng|em không|em đã|em sẽ|em quay về|em ra đi|em buông tay|cô gái|nàng thơ)\b/g) || []).length;
    const maleSignals = (combined.match(/\b(anh yêu em|anh nhớ em|nhớ em|yêu em|bên em|gần em|đợi em|chờ em|cần em|vì em|với em|của em|em ơi|cho anh|với anh|của anh|chính anh|bản thân anh|anh nghĩ|anh thấy|anh muốn|anh biết|anh khóc|anh mơ|anh sợ|anh bước|anh đau|anh chẳng|anh không|anh đã|anh sẽ|anh quay về|anh ra đi|anh buông tay|chàng trai)\b/g) || []).length;

    if (femaleSignals > 0 && femaleSignals >= maleSignals) {
      currentSongPronounRole = 'female';
      console.log('[YT ViSub] [Gemini Pronoun Lock] Anchored song perspective to FEMALE (Em - Anh).');
    } else if (maleSignals > 0 && maleSignals > femaleSignals) {
      currentSongPronounRole = 'male';
      console.log('[YT ViSub] [Gemini Pronoun Lock] Anchored song perspective to MALE (Anh - Em).');
    }
  }

  /**
   * Get current video playback time in milliseconds
   */
  function getVideoCurrentTimeMs() {
    try {
      const video = attachedVideoElement || (playerElement ? playerElement.querySelector('video') : document.querySelector('video'));
      if (video && !isNaN(video.currentTime)) {
        return Math.floor(video.currentTime * 1000);
      }
    } catch (_) {}
    return 0;
  }

  /**
   * Normalize string for fast cache keys
   */
  function normalizeText(str) {
    if (!str) return '';
    return str.replace(/\s+/g, ' ').trim();
  }

  /**
   * Helper to decode HTML entities
   */
  function decodeHtmlEntities(str) {
    if (!str) return '';
    return str
      .replace(/&quot;/g, '"')
      .replace(/&#39;/g, "'")
      .replace(/&apos;/g, "'")
      .replace(/&amp;/g, '&')
      .replace(/&lt;/g, '<')
      .replace(/&gt;/g, '>')
      .replace(/&#(\d+);/g, (_, code) => String.fromCharCode(code));
  }

  /**
   * Fast script detection for CJK, Cyrillic, Arabic, Thai, etc.
   */
  function detectScriptLanguage(text) {
    if (!text) return '';
    // Japanese: Hiragana or Katakana
    if (/[\u3040-\u309F\u30A0-\u30FF]/.test(text)) return 'ja';
    // Korean: Hangul
    if (/[\uAC00-\uD7AF\u1100-\u11FF]/.test(text)) return 'ko';
    // Chinese: Han characters without Kana
    if (/[\u4E00-\u9FFF\u3400-\u4DBF]/.test(text)) return 'zh';
    // Russian / Cyrillic
    if (/[\u0400-\u04FF]/.test(text)) return 'ru';
    // Arabic
    if (/[\u0600-\u06FF]/.test(text)) return 'ar';
    // Thai
    if (/[\u0E00-\u0E7F]/.test(text)) return 'th';
    // Greek
    if (/[\u0370-\u03FF]/.test(text)) return 'el';
    // Hebrew
    if (/[\u0590-\u05FF]/.test(text)) return 'he';
    return '';
  }

  /**
   * Determine exact source language code (e.g. ja, ko, en) when auto-detection is active
   */
  function resolveSourceLang(text, configuredSourceLang) {
    if (configuredSourceLang && configuredSourceLang !== 'auto') {
      return configuredSourceLang;
    }
    const detected = detectScriptLanguage(text);
    if (detected) {
      return detected;
    }
    if (detectedCaptionLang) {
      return detectedCaptionLang;
    }
    return 'en';
  }

  /**
   * Check if text is already written in the target language (e.g. Vietnamese)
   */
  function isAlreadyTargetLanguage(text, targetLang) {
    if (!text) return false;
    const tl = targetLang || 'vi';
    if (tl === 'vi') {
      return /[àáạảãâầấậẩẫăằắặẳẵèéẹẻẽêềếệểễìíịỉĩòóọỏõôồốộổỗơờớợởỡùúụủũưừứựửữỳýỵỷỹđ]/i.test(text);
    }
    return false;
  }

  /**
   * Inspect YouTube DOM menu items to detect if an auto-generated subtitle track is active
   */
  function checkDomForAsrCaption() {
    try {
      const activeItem = document.querySelector('.ytp-menuitem[aria-checked="true"]');
      if (activeItem && activeItem.textContent) {
        const text = activeItem.textContent.toLowerCase();
        if (text.includes('được tạo tự động') || text.includes('auto-generated') || text.includes('tự động tạo') || text.includes('自動生成') || text.includes('자동 생성')) {
          return true;
        }
      }
    } catch (_) {}
    return false;
  }

  /**
   * Determine effective translation service:
   * When user selects Gemini AI, but the active subtitle is auto-generated by YouTube (ASR),
   * seamlessly route to Google Translate so subtitles are STILL translated & displayed,
   * while completely bypassing Gemini to save API quota and avoid spam requests!
   */
  function getEffectiveService() {
    const configured = settings.translationService || 'google';
    if (configured === 'gemini' && (isAutoGeneratedTrack || checkDomForAsrCaption())) {
      return 'google';
    }
    return configured;
  }

  /**
   * Determine if Gemini should be bypassed to avoid spamming requests and save user quota
   * (e.g. YouTube auto-translate active, auto-generated ASR captions, or already translated)
   */
  function shouldBypassGemini(text = '') {
    if (isYouTubeAutoTranslateActive) return true;
    if (isAutoGeneratedTrack || checkDomForAsrCaption()) return true;
    if (text && isAlreadyTargetLanguage(text, settings.targetLang)) return true;
    return false;
  }

  /**
   * Check if active subtitle matches target language (e.g. Vietnamese subtitles -> Vietnamese target)
   */
  function isTrackMatchingTargetLanguage(text = '') {
    const tl = (settings.targetLang || 'vi').toLowerCase();
    if (detectedCaptionLang) {
      const detected = detectedCaptionLang.toLowerCase();
      if (detected === tl || detected.startsWith(`${tl}-`) || tl.startsWith(`${detected}-`)) {
        return true;
      }
    }
    if (tl === 'vi' && text) {
      if (isAlreadyTargetLanguage(text, 'vi')) {
        return true;
      }
    }
    return false;
  }

  /**
   * Update visibility of native YouTube captions vs custom extension overlay
   * When subtitle language matches target language, show YouTube's native subtitle
   * and hide custom overlay to avoid duplicate lines and eliminate 3rd-party/Gemini calls.
   */
  function updateNativeSubtitleVisibility(isSameAsTarget = false) {
    if (!playerElement) return;

    if (isSameAsTarget) {
      // Subtitle is already in target language: Let YouTube display its native caption!
      if (playerElement.classList.contains('ytsub-hide-native')) {
        playerElement.classList.remove('ytsub-hide-native');
      }
      if (innerBox && !innerBox.classList.contains('ytsub-hidden')) {
        innerBox.classList.add('ytsub-hidden');
      }
    } else {
      // Different language: Hide native caption if configured, show custom translator overlay
      const shouldHide = settings.enabled && settings.displayMode !== 'off' && settings.hideOriginalNative;
      if (shouldHide) {
        if (!playerElement.classList.contains('ytsub-hide-native')) {
          playerElement.classList.add('ytsub-hide-native');
        }
      } else {
        if (playerElement.classList.contains('ytsub-hide-native')) {
          playerElement.classList.remove('ytsub-hide-native');
        }
      }
    }
  }

  /**
   * Match chronological subtitle cues with YouTube native pre-translated cues
   * Caches translations across all engines to bypass Gemini API calls completely
   */
  function matchTimedCuesWithNativeTranslations(cues) {
    if (!cues || cues.length === 0 || nativeTranslationsByMs.size === 0) return;
    const sl = settings.sourceLang || 'auto';
    const tl = settings.targetLang || 'vi';
    let countMatched = 0;

    cues.forEach((c) => {
      let trans = nativeTranslationsByMs.get(c.startMs);
      if (!trans) {
        for (const [ms, text] of nativeTranslationsByMs.entries()) {
          if (Math.abs(ms - c.startMs) <= 250) {
            trans = text;
            break;
          }
        }
      }

      if (trans && trans !== c.text) {
        nativeTranslationsByText.set(c.text, trans);
        // CRITICAL: When user selects Gemini AI, NEVER poison Gemini cache with raw machine YouTube translations!
        // Gemini AI will translate with rich poetic emotion and consistent pronouns.
        if (settings.translationService !== 'gemini') {
          localCache.set(getCacheKey(settings.translationService, sl, tl, c.text), trans);
          localCache.set(getCacheKey('gemini', sl, tl, c.text), trans);
        }
        localCache.set(getCacheKey('google', sl, tl, c.text), trans);
        localCache.set(getCacheKey('youtube', sl, tl, c.text), trans);
        countMatched++;
      }
    });

    if (countMatched > 0) {
      chrome.runtime.sendMessage({ action: 'RECORD_QUOTA_SAVED', count: countMatched }).catch(() => {});
      console.log(`[YT ViSub] Matched ${countMatched} cues from YouTube auto-translation into localCache. Gemini quota saved.`);
    }
  }

  /**
   * Comprehensive multilingual dictionary for sound, action, and music cues
   * (Japanese, Chinese, Korean, English) -> Vietnamese
   */
  const SOUND_CUE_MAP = {
    // Clapping / Applause
    '拍手': 'Vỗ tay',
    'applause': 'Tiếng vỗ tay',
    'clapping': 'Tiếng vỗ tay',
    'clap': 'Vỗ tay',
    'cheering': 'Tiếng reo hò',
    'cheers': 'Tiếng reo hò',
    'cheer': 'Tiếng reo hò',
    '歓声': 'Tiếng reo hò',
    '박수': 'Tiếng vỗ tay',
    '환호': 'Tiếng reo hò',

    // Laughing / Laughter
    '笑': 'Cười',
    '笑い': 'Tiếng cười',
    'laughter': 'Tiếng cười',
    'laughing': 'Tiếng cười',
    'laughs': 'Cười',
    'laugh': 'Cười',
    'giggle': 'Cười khúc khích',
    'giggling': 'Cười khúc khích',
    'chuckle': 'Cười thầm',
    'chuckling': 'Cười thầm',
    '웃음': 'Tiếng cười',

    // Sighing / Gasping
    'ため息': 'Thở dài',
    'sigh': 'Thở dài',
    'sighs': 'Thở dài',
    'sighing': 'Thở dài',
    'gasp': 'Kinh ngạc',
    'gasps': 'Kinh ngạc',
    'gasping': 'Kinh ngạc',
    '息をのむ': 'Nín thở',
    '탄식': 'Thở dài',

    // Crying / Screaming
    '泣き声': 'Tiếng khóc',
    'crying': 'Tiếng khóc',
    'cries': 'Tiếng khóc',
    'sob': 'Nấc nở',
    'sobs': 'Nấc nở',
    'sobbing': 'Nấc nở',
    'screaming': 'Tiếng hét',
    'screams': 'Tiếng hét',
    'scream': 'Tiếng hét',
    'shout': 'Tiếng la',
    'shouting': 'Tiếng la',
    '悲鳴': 'Tiếng hét',
    '비명': 'Tiếng hét',

    // Cough / Sneeze
    'cough': 'Tiếng ho',
    'coughing': 'Tiếng ho',
    'coughs': 'Tiếng ho',
    '咳': 'Tiếng ho',
    'sneeze': 'Hắt hơi',
    'sneezing': 'Hắt hơi',
    'くしゃみ': 'Hắt hơi',

    // Music / Noise
    'music': 'Âm nhạc',
    'bgm': 'Nhạc nền',
    '音楽': 'Âm nhạc',
    '음악': 'Âm nhạc',
    'instrumental': 'Nhạc không lời',
    'theme music': 'Nhạc chủ đề',
  };

  /**
   * Resolve non-speech, action, and sound cues offline (0ms, 0 API quota)
   * Examples: (拍手), [Applause], (笑), [Music], ♪, ♫
   */
  function resolveSoundCueOffline(text) {
    if (!text) return '';
    const trimmed = text.trim();

    // Check musical symbols alone
    if (/^[♪♫🎵\s\-–—]+$/.test(trimmed)) {
      return trimmed;
    }

    // Check if whole text is enclosed in brackets or parentheses
    // e.g. (拍手), [Applause], （笑い）, 【歓声】
    const bracketMatch = trimmed.match(/^[\(\[\{（【〔〈《](.+?)[\)\]\}）】〕〉》]$/);
    if (bracketMatch) {
      const inner = bracketMatch[1].trim().toLowerCase();
      for (const [key, val] of Object.entries(SOUND_CUE_MAP)) {
        if (inner === key.toLowerCase() || inner.includes(key.toLowerCase())) {
          const openChar = trimmed[0];
          const closeChar = trimmed[trimmed.length - 1];
          return `${openChar}${val}${closeChar}`;
        }
      }
      if (/^[♪♫🎵\s]+$/.test(inner)) {
        return trimmed;
      }
    }

    // Direct standalone sound word
    const lower = trimmed.toLowerCase();
    if (SOUND_CUE_MAP[lower]) {
      return `(${SOUND_CUE_MAP[lower]})`;
    }

    return '';
  }
  /**
   * Extract video title from YouTube page DOM for contextual translation
   */
  function getVideoTitle() {
    try {
      const titleElem = document.querySelector('ytd-watch-metadata #title h1 yt-formatted-string') ||
                        document.querySelector('#title h1 yt-formatted-string') ||
                        document.querySelector('h1.ytd-video-primary-info-renderer') ||
                        document.querySelector('.ytp-title-link');
      if (titleElem && titleElem.textContent) {
        return titleElem.textContent.trim();
      }
      if (document.title) {
        return document.title.replace(/\s*-\s*YouTube$/i, '').trim();
      }
    } catch (_) {}
    return '';
  }

  /**
   * Extract channel or artist name from YouTube page DOM
   */
  function getChannelName() {
    try {
      const channelElem = document.querySelector('ytd-watch-metadata ytd-channel-name yt-formatted-string a') ||
                          document.querySelector('ytd-watch-metadata #channel-name a') ||
                          document.querySelector('#upload-info ytd-channel-name a') ||
                          document.querySelector('ytd-video-owner-renderer ytd-channel-name a') ||
                          document.querySelector('#owner #channel-name a');
      if (channelElem && channelElem.textContent) {
        return channelElem.textContent.trim();
      }
    } catch (_) {}
    return '';
  }

  /**
   * Extract comprehensive video metadata (Genre, Artist/Guests, Show/Channel, Title)
   */
  function extractVideoMetadata() {
    let genre = 'general';
    let artist = '';
    let song = '';
    let show = '';
    let guest = '';
    const rawTitle = getVideoTitle();
    const channel = getChannelName();
    const titleLower = rawTitle.toLowerCase();
    const channelLower = channel.toLowerCase();

    // 1. Check YouTube official music metadata row in description
    try {
      const rows = document.querySelectorAll('ytd-metadata-row-renderer');
      for (const row of rows) {
        const titleEl = row.querySelector('#title') || row.querySelector('h4');
        const contentEl = row.querySelector('#content') || row.querySelector('#default-metadata');
        if (titleEl && contentEl) {
          const label = titleEl.textContent.trim().toLowerCase();
          if (label.includes('artist') || label.includes('nghệ sĩ') || label.includes('performer')) {
            artist = contentEl.textContent.trim();
            genre = 'music';
            break;
          }
          if (label.includes('song') || label.includes('bài hát') || label.includes('album')) {
            genre = 'music';
          }
        }
      }
    } catch (_) {}

    // 2. Check for News / Journalism / Reportage
    const newsBrands = /\b(bbc|cnn|cnbc|bloomberg|reuters|vtv|vtv24|tuổi trẻ|thanh niên|vnexpress|vox|the guardian|abc news|cbs news|fox news|al jazeera|dw|nhk|channel 4 news|sky news|ap archive|france 24|msnbc|pbs news|thời sự)\b/i;
    const newsKeywords = /\b(news|breaking news|thời sự|bản tin|phóng sự|điều tra|tài liệu|documentary|press conference|họp báo|reportage|investigation|báo cáo|tạp chí kinh tế|tổng thống|thủ tướng|chính phủ)\b/i;
    
    if (newsBrands.test(channelLower) || newsKeywords.test(titleLower)) {
      genre = 'news';
    }

    // 3. Check for Reality Show / Variety Show / Talk Show / Podcast / Interview / Japanese Idol Shows
    const showKeywords = /\b(running man|2 ngày 1 đêm|knowing bros|talkshow|podcast|phỏng vấn|interview|hot ones|the tonight show|late night|graham norton|game show|challenge|weekly idol|amazing saturday|street woman fighter|single's inferno|show me the money|ted talk|vogue 73 questions|vui vẻ|tập\s+\d+|ep\.\s*\d+|episode\s*\d+|show thực tế)\b/i;
    const jpIdolShowPattern = /(乃木坂工事中|nogizaka under construction|そこ曲がったら[、,]?\s*櫻坂|日向坂で会いましょう|乃木坂どこへ|スター誕生|超・乃木坂スター誕生|akbingo|サヨナラ毛利さん|モニタリング|水曜日のダウンタウン|ロンドンハーツ|アメトーーク|しゃべくり007|それsnow man|vs嵐|嵐にしやがれ|月曜から夜ふかし)/i;

    const isShowDetected = genre !== 'news' && (showKeywords.test(titleLower) || showKeywords.test(channelLower) || jpIdolShowPattern.test(rawTitle) || jpIdolShowPattern.test(channel));
    if (isShowDetected) {
      genre = 'reality_show';

      // 3.1 Check Japanese Idol Variety Shows first
      const jpMatch = rawTitle.match(jpIdolShowPattern) || channel.match(jpIdolShowPattern);
      if (jpMatch) {
        show = jpMatch[1].trim();
        const epMatch = rawTitle.match(/#\s*(\d+)|第\s*(\d+)\s*回|ep\.?\s*(\d+)/i);
        if (epMatch) {
          show += ` #${epMatch[1] || epMatch[2] || epMatch[3]}`;
        }
        if (/乃木坂/i.test(rawTitle)) guest = '乃木坂46';
        else if (/櫻坂/i.test(rawTitle)) guest = '櫻坂46';
        else if (/日向坂/i.test(rawTitle)) guest = '日向坂46';
        else if (/akb/i.test(rawTitle)) guest = 'AKB48 Group';
      }

      // 3.2 Try to parse guest / artist from reality show title
      if (!guest) {
        const guestMatch = rawTitle.match(/(?:with|khách mời[:\s]|featuring|ft\.?|gặp gỡ|phỏng vấn)\s+([^,\-\|\(\)\[\]]{2,40})/i);
        if (guestMatch) {
          guest = guestMatch[1].trim();
        }
      }
      if (!show) {
        const showMatch = rawTitle.match(/^\[([^\]]+)\]|^([^:\|\-]+?)(?:\s*(?:ep\.?\s*\d+|tập\s*\d+|khách mời|with|phỏng vấn))/i);
        if (showMatch) {
          show = (showMatch[1] || showMatch[2]).trim();
        }
      }
    }

    // 4. Check for Music / Songs (if not news/show)
    const musicKeywords = /\b(mv|official music video|official video|lyric video|lyrics|audio|visualizer|m\/v|cover|remix|ft\.|feat\.|nhạc|bài hát|ca khúc|ost|soundtrack|live session|single|album|op|ed|theme|vocal|song|instrumental)\b|♪|♫|主題歌|挿入歌|楽曲|新曲|メドレー|乃木坂46|櫻坂46|日向坂46|欅坂46|akb48|ske48|nmb48|hkt48|=love|≠me|≒joy|モーニング娘|ももいろクローバー|ヨルシカ|ずとまよ|ずっと真夜中|結束バンド|初音ミク/i;
    if (genre !== 'news' && genre !== 'reality_show') {
      if (musicKeywords.test(titleLower) || artist) {
        genre = 'music';
      }
    }

    // Parse Artist - Song format if music
    if (genre === 'music' || (!artist && !guest)) {
      const clean = rawTitle.replace(/[\(\[\{【〔〈《].*?(official|mv|video|lyrics|audio|visualizer|m\/v|ep\.\s*\d+|tập\s*\d+).*?[\)\]\}】〕〉》]/gi, '').trim();

      // 1. Standard delimiters: Artist - Song / Artist | Song / Artist / Song / Artist _ Song
      let match = clean.match(/^([^\-\–\—\|\/_]{2,45})\s*[\-\–\—\|\/_]\s*(.+)$/);

      // 2. Japanese quotation marks: Artist「Song」 or Artist『Song』
      if (!match) {
        const jMatch = clean.match(/^([^\u300C\u300E]{2,40})[\u300C\u300E](.+?)[\u300D\u300F]/);
        if (jMatch) match = jMatch;
      }

      // 3. Korean / Quote format: Artist 'Song' or Artist "Song"
      if (!match) {
        const qMatch = clean.match(/^([^'"]{2,40})\s*['"](.+?)['"]/);
        if (qMatch) match = qMatch;
      }

      if (match) {
        if (genre === 'music') {
          if (!artist) artist = match[1].trim();
          song = match[2].trim();
        } else if (genre === 'reality_show') {
          if (!guest) guest = match[2].trim();
        }
      }
    }

    // Clean artist name (strip leading bracket tags, feat, official, alternate script)
    if (artist) {
      artist = artist
        .replace(/^\[.*?\]\s*/, '')
        .replace(/\(feat\..*?\)/i, '')
        .replace(/\(ft\..*?\)/i, '')
        .replace(/\s*\(.*?\)$/, '')
        .replace(/^(MV|M\/V|Official MV)\s*[-|:]\s*/i, '')
        .trim();
    }

    // Fallback artist to channel name if music
    if (genre === 'music' && !artist) {
      if (channel) {
        artist = channel
          .replace(/\s*-\s*Topic$/i, '')
          .replace(/Official(\s*Channel|\s*Artist|\s*VEVO)?$/i, '')
          .replace(/\s*VEVO$/i, '')
          .replace(/\s*Music$/i, '')
          .trim();
      }
    }

    return {
      genre,
      artist: artist || '',
      song: song || '',
      show: show || '',
      guest: guest || '',
      channel: channel || '',
      fullTitle: rawTitle || ''
    };
  }

  /**
   * Extract comprehensive video context (Genre, Entities, Artist, Song, and Title)
   */
  function getVideoContext() {
    const meta = extractVideoMetadata();
    const parts = [];
    if (meta.genre && meta.genre !== 'general') parts.push(`Genre: ${meta.genre}`);
    if (meta.show) parts.push(`Show: ${meta.show}`);
    if (meta.channel) parts.push(`Channel: ${meta.channel}`);
    if (meta.artist) parts.push(`Artist: ${meta.artist}`);
    if (meta.guest) parts.push(`Guest/Figure: ${meta.guest}`);
    if (meta.song && meta.song !== meta.fullTitle) parts.push(`Song: ${meta.song}`);
    if (meta.fullTitle) parts.push(`Title: ${meta.fullTitle}`);
    return parts.join(' | ') || meta.fullTitle || '';
  }

  /**
   * Standardize cache key across local synchronous cache and pre-translation
   * For Gemini AI, cache is scoped to the current video to guarantee 100% pronoun consistency
   */
  function getCacheKey(service, sl, tl, text) {
    const s = service || 'google';
    const currentVideo = getVideoTitle();
    const anchorKey = s === 'gemini' && currentVideo ? `:${currentVideo.slice(0, 50).toLowerCase().trim()}` : '';
    const stylePart = s === 'gemini' ? `:${settings.geminiStyle || 'auto'}:${settings.geminiPronounRole || 'auto'}` : '';
    return `${s}${stylePart}${anchorKey}:${sl || 'auto'}->${tl || 'vi'}:${text}`;
  }

  /**
   * Send config to inject.js in main world
   */
  function syncConfigToMainWorld() {
    window.postMessage({
      source: 'YTSUB_CONTENT_CONFIG',
      targetLang: settings.targetLang || 'vi',
      service: settings.translationService || 'google',
    }, '*');
  }

  /**
   * Load settings from storage
   */
  async function loadSettings() {
    try {
      const stored = await chrome.storage.sync.get(Object.keys(settings));
      // Auto-migrate legacy default 60 to 0 (0 = automatic responsive elevation above player controls)
      if (stored.subBottomOffset === 60) {
        stored.subBottomOffset = 0;
        chrome.storage.sync.set({ subBottomOffset: 0 }).catch(() => {});
      }
      // Auto-migrate legacy 1.5/2.0 models to gemini-3.5-flash-lite
      if (stored.geminiModel && (stored.geminiModel.includes('1.5') || stored.geminiModel.includes('2.0'))) {
        stored.geminiModel = 'gemini-3.5-flash-lite';
        chrome.storage.sync.set({ geminiModel: 'gemini-3.5-flash-lite' }).catch(() => {});
      }
      settings = { ...settings, ...stored };
      applySettings();
      syncConfigToMainWorld();
    } catch (err) {
      console.warn('[YT ViSub] Could not load settings:', err);
    }
  }

  let lastAppliedFontSize = 0;
  let cachedNativeFs = 0;
  let lastNativeFsCheck = 0;

  /**
   * Check if YouTube player or page is in fullscreen mode
   */
  function isPlayerFullscreen() {
    if (playerElement && playerElement.classList.contains('ytp-fullscreen')) {
      return true;
    }
    if (document.fullscreenElement) {
      return true;
    }
    return false;
  }

  /**
   * Inspect YouTube's native subtitle elements to read its authentic font size.
   * Cached for 2s to eliminate layout thrashing and forced reflows.
   */
  function getNativeCaptionFontSize() {
    if (!playerElement) return 0;
    const now = Date.now();
    if (cachedNativeFs > 0 && now - lastNativeFsCheck < 2000) {
      return cachedNativeFs;
    }

    const container = playerElement.querySelector('.ytp-caption-window-container');
    if (!container) return cachedNativeFs;

    // Check individual caption segments
    const segments = container.querySelectorAll('.ytp-caption-segment');
    for (const seg of segments) {
      const fs = parseFloat(window.getComputedStyle(seg).fontSize);
      if (fs && fs >= 12 && fs <= 120) {
        cachedNativeFs = fs;
        lastNativeFsCheck = now;
        return fs;
      }
    }

    // Check caption window blocks
    const windows = container.querySelectorAll('.caption-window');
    for (const win of windows) {
      const fs = parseFloat(window.getComputedStyle(win).fontSize);
      if (fs && fs >= 12 && fs <= 120) {
        cachedNativeFs = fs;
        lastNativeFsCheck = now;
        return fs;
      }
    }

    return cachedNativeFs;
  }

  /**
   * Dynamically calculate effective font size based on fullscreen state,
   * player dimensions and user settings (with authentic YouTube native synchronization).
   */
  function computeEffectiveFontSize() {
    const baseFs = Math.max(12, settings.fontSize || 20);

    if (!isPlayerFullscreen() || settings.fullscreenOptimize === false) {
      return baseFs;
    }

    const mode = settings.fullscreenScaleMode || 'sync_yt';

    if (mode === 'sync_yt') {
      const nativeFs = getNativeCaptionFontSize();
      if (nativeFs > 0) {
        // Synchronized directly with YouTube native captions
        if (baseFs === 20) {
          return Math.round(nativeFs);
        }
        // Scale proportionally if user set a non-default base size
        return Math.max(16, Math.min(80, Math.round(nativeFs * (baseFs / 20))));
      }

      // Fallback when native CC is inactive or not yet rendered in DOM:
      // YouTube native subtitle standard size is ~3.0% - 3.2% of player height in fullscreen
      const playerHeight = (playerElement && playerElement.clientHeight > 0)
        ? playerElement.clientHeight
        : (window.innerHeight || 1080);

      const ytStandardFs = Math.max(24, Math.round(playerHeight * 0.0315));
      if (baseFs === 20) {
        return ytStandardFs;
      }
      return Math.max(16, Math.min(80, Math.round(ytStandardFs * (baseFs / 20))));
    }

    if (mode === 'custom') {
      const customFs = settings.fullscreenCustomSize || 32;
      return Math.max(14, Math.min(80, customFs));
    }

    // Fixed scale multiplier (e.g. 1.25, 1.4, 1.5, 1.75, 2.0)
    const factor = parseFloat(mode);
    if (!isNaN(factor) && factor > 0) {
      return Math.max(16, Math.min(80, Math.round(baseFs * factor)));
    }

    return baseFs;
  }

  /**
   * Apply settings to the DOM and overlay
   */
  function applySettings() {
    if (!overlayContainer || !innerBox) return;

    if (!settings.enabled || settings.displayMode === 'off') {
      overlayContainer.style.display = 'none';
      if (document.body && document.body.classList.contains('ytsub-active')) {
        document.body.classList.remove('ytsub-active');
      }
      if (playerElement && playerElement.classList.contains('ytsub-hide-native')) {
        playerElement.classList.remove('ytsub-hide-native');
      }
      return;
    }

    overlayContainer.style.display = 'flex';
    if (document.body && !document.body.classList.contains('ytsub-active')) {
      document.body.classList.add('ytsub-active');
    }

    if (playerElement) {
      const shouldHide = !isTrackMatchingTargetLanguage() && settings.hideOriginalNative;
      if (shouldHide) {
        if (!playerElement.classList.contains('ytsub-hide-native')) {
          playerElement.classList.add('ytsub-hide-native');
        }
      } else {
        if (playerElement.classList.contains('ytsub-hide-native')) {
          playerElement.classList.remove('ytsub-hide-native');
        }
      }
    }

    // Unified box background: apply directly to innerBox container
    const bgVal = `rgba(8, 8, 8, ${(settings.bgOpacity ?? 75) / 100})`;
    innerBox.style.backgroundColor = bgVal;

    // Calculate responsive effective font size
    const effectiveFontSize = computeEffectiveFontSize();
    lastAppliedFontSize = effectiveFontSize;

    if (overlayContainer) {
      overlayContainer.style.setProperty('--ytsub-font-size', `${effectiveFontSize}px`);
    }

    if (originalTextElement) {
      originalTextElement.style.fontSize = `${Math.round(effectiveFontSize * 0.92)}px`;
      originalTextElement.style.color = settings.originalColor || '#FFFFFF';
      originalTextElement.style.backgroundColor = 'transparent';
    }

    if (translatedTextElement) {
      translatedTextElement.style.fontSize = `${effectiveFontSize}px`;
      translatedTextElement.style.color = settings.fontColor || '#FFFFFF';
      translatedTextElement.style.backgroundColor = 'transparent';
    }

    if (origWrapper) {
      origWrapper.style.display = settings.displayMode === 'bilingual' ? 'block' : 'none';
    }

    if (settings.subPosition === 'top') {
      overlayContainer.classList.add('ytsub-pos-top');
    } else {
      overlayContainer.classList.remove('ytsub-pos-top');
      if (!isDragging) {
        if (settings.subBottomOffset && settings.subBottomOffset !== 0) {
          overlayContainer.style.setProperty('--ytsub-user-offset', `${settings.subBottomOffset}px`);
        } else {
          overlayContainer.style.removeProperty('--ytsub-user-offset');
        }
      }
    }
  }

  /**
   * Create or retrieve subtitle overlay container matching native YouTube caption structure
   */
  function setupOverlay(player) {
    if (!player) return;

    let container = player.querySelector('#ytsub-overlay-container');
    if (!container) {
      container = document.createElement('div');
      container.id = 'ytsub-overlay-container';

      const box = document.createElement('div');
      box.id = 'ytsub-inner-box';
      box.classList.add('ytsub-hidden');

      const origWrap = document.createElement('div');
      origWrap.id = 'ytsub-orig-wrapper';
      origWrap.className = 'ytsub-line-wrapper';

      const origText = document.createElement('span');
      origText.id = 'ytsub-original-text';
      origText.className = 'ytsub-line';
      origWrap.appendChild(origText);

      const transWrap = document.createElement('div');
      transWrap.id = 'ytsub-trans-wrapper';
      transWrap.className = 'ytsub-line-wrapper';

      const transText = document.createElement('span');
      transText.id = 'ytsub-translated-text';
      transText.className = 'ytsub-line';
      transWrap.appendChild(transText);

      box.appendChild(origWrap);
      box.appendChild(transWrap);
      container.appendChild(box);

      player.appendChild(container);

      setupDraggable(box, container, player);
    }

    overlayContainer = container;
    innerBox = container.querySelector('#ytsub-inner-box');
    origWrapper = container.querySelector('#ytsub-orig-wrapper');
    transWrapper = container.querySelector('#ytsub-trans-wrapper');
    originalTextElement = container.querySelector('#ytsub-original-text');
    translatedTextElement = container.querySelector('#ytsub-translated-text');

    applySettings();
  }

  /**
   * Vertical drag handler
   */
  function setupDraggable(box, container, player) {
    let startUserOffset = 0;

    const onMouseDown = (e) => {
      if (e.button !== 0) return;
      isDragging = true;
      startY = e.clientY;
      const currentProp = container.style.getPropertyValue('--ytsub-user-offset');
      startUserOffset = currentProp ? parseInt(currentProp, 10) || 0 : (settings.subBottomOffset || 0);
      container.style.transition = 'none';

      document.addEventListener('mousemove', onMouseMove);
      document.addEventListener('mouseup', onMouseUp);
      e.preventDefault();
    };

    const onMouseMove = (e) => {
      if (!isDragging) return;
      const deltaY = startY - e.clientY;
      const newOffset = Math.max(-60, Math.min(player.clientHeight - 150, startUserOffset + deltaY));
      container.style.setProperty('--ytsub-user-offset', `${newOffset}px`);
    };

    const onMouseUp = () => {
      if (!isDragging) return;
      isDragging = false;
      container.style.removeProperty('transition');
      document.removeEventListener('mousemove', onMouseMove);
      document.removeEventListener('mouseup', onMouseUp);

      const prop = container.style.getPropertyValue('--ytsub-user-offset');
      const savedOffset = prop ? parseInt(prop, 10) || 0 : 0;
      settings.subBottomOffset = savedOffset;
      chrome.storage.sync.set({ subBottomOffset: savedOffset }).catch(() => {});
    };

    box.addEventListener('mousedown', onMouseDown);
  }

  /**
   * Fast Google Gemini AI translation (Routed through Background Worker to bypass YouTube CSP)
   */
  async function fetchGeminiTranslation(text, sourceLang, targetLang, apiKey, signal, model, style, pronounRole) {
    if (!apiKey || !apiKey.trim()) throw new Error('Missing Gemini API Key');
    const tl = targetLang || 'vi';
    let chosenModel = model || settings.geminiModel || 'gemini-3.5-flash-lite';
    if (chosenModel.includes('lite')) {
      chosenModel = 'gemini-3.5-flash-lite';
    } else if (chosenModel.includes('3.5')) {
      chosenModel = 'gemini-3.5-flash';
    } else if (chosenModel.includes('2.0') || chosenModel.includes('1.5')) {
      chosenModel = 'gemini-3.5-flash-lite';
    }
    const currentVideoContext = getVideoContext();
    const currentStyle = style || settings.geminiStyle || 'auto';
    const currentPronoun = pronounRole || settings.geminiPronounRole || 'auto';

    // 1. Primary: Route via Background Service Worker (100% immune to YouTube page CSP)
    try {
      const bgResult = await new Promise((resolve, reject) => {
        chrome.runtime.sendMessage({
          action: 'TRANSLATE',
          text: text,
          sourceLang: sourceLang || 'auto',
          targetLang: tl,
          service: 'gemini',
          apiKey: apiKey.trim(),
          model: chosenModel,
          videoTitle: currentVideoContext,
          style: currentStyle,
          pronounRole: currentPronoun,
        }, (res) => {
          if (chrome.runtime.lastError) {
            return reject(new Error(chrome.runtime.lastError.message));
          }
          if (res && res.success && res.translation) {
            return resolve(res.translation);
          }
          reject(new Error(res?.error || 'Gemini returned empty'));
        });
      });

      if (bgResult) {
        return bgResult;
      }
    } catch (bgErr) {
      console.warn('[YT ViSub] [Gemini AI] Background worker error, trying direct fetch...', bgErr.message);
    }

    // 2. Direct fetch fallback
    const targetName = tl === 'vi' ? 'Vietnamese' : tl;
    const url = `https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(chosenModel)}:generateContent?key=${encodeURIComponent(apiKey.trim())}`;
    const prompt = `Translate this subtitle line directly to natural, conversational ${targetName}. Keep it concise for video subtitles. Output ONLY the translated text, no quotes, no extra explanations:\n${text}`;

    const res = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [{ parts: [{ text: prompt }] }],
        generationConfig: {
          temperature: 0.1,
          maxOutputTokens: 60
        }
      }),
      signal: signal,
      keepalive: true
    });

    if (!res.ok) {
      const errText = await res.text();
      throw new Error(`Gemini API HTTP ${res.status}: ${errText}`);
    }

    const data = await res.json();
    const rawText = data?.candidates?.[0]?.content?.parts?.[0]?.text;
    if (rawText && typeof rawText === 'string') {
      const cleaned = rawText
        .trim()
        .replace(/^["'“”«»]+|["'“”«»]+$/g, '')
        .replace(/^(Bản dịch|Translation):\s*/i, '')
        .trim();
      if (cleaned) {
        return decodeHtmlEntities(cleaned);
      }
    }

    throw new Error('Invalid response structure from Gemini API');
  }

  /**
   * Fast direct translation (Google Translate, MyMemory or Gemini with auto failover)
   */
  async function fetchDirectTranslation(text, sourceLang, targetLang, service, signal) {
    const sl = sourceLang || 'auto';
    const tl = targetLang || 'vi';

    // If Gemini AI engine selected
    if (service === 'gemini') {
      if (settings.geminiApiKey) {
        try {
          const geminiTrans = await fetchGeminiTranslation(
            text,
            sl,
            tl,
            settings.geminiApiKey,
            signal,
            settings.geminiModel || 'gemini-3.5-flash-lite',
            settings.geminiStyle || 'auto',
            settings.geminiPronounRole || 'auto'
          );
          if (geminiTrans) {
            return geminiTrans;
          }
        } catch (err) {
          if (err.name === 'AbortError' && signal && signal.aborted) {
            throw err;
          }
          console.warn('[YT ViSub] Gemini translation failed, auto-failover to Google Translate...', err);
        }
      }
      // If Gemini key missing or failed, seamlessly fall back to Google Translate!
    }

    // If MyMemory engine selected
    if (service === 'mymemory') {
      const resolvedSl = resolveSourceLang(text, sl);
      const pair = `${resolvedSl}|${tl}`;
      try {
        const url = `https://api.mymemory.translated.net/get?q=${encodeURIComponent(text)}&langpair=${encodeURIComponent(pair)}`;
        const timeoutController = new AbortController();
        const timeoutTimer = setTimeout(() => timeoutController.abort(), 2000);
        const onAbort = () => timeoutController.abort();
        if (signal) signal.addEventListener('abort', onAbort);

        const res = await fetch(url, { signal: timeoutController.signal, keepalive: true });
        clearTimeout(timeoutTimer);
        if (signal) signal.removeEventListener('abort', onAbort);

        if (res.ok) {
          const json = await res.json();
          const rawTrans = json.responseData?.translatedText;
          if (rawTrans && typeof rawTrans === 'string') {
            const decoded = decodeHtmlEntities(rawTrans).trim();
            const upper = decoded.toUpperCase();
            const isWarning = upper.includes('MYMEMORY WARNING') || 
                              upper.includes('INVALID LANGUAGE PAIR') || 
                              upper.includes('NO QUERY SPECIFIED') ||
                              upper.includes('DAILY LIMIT') ||
                              upper.includes('QUERY LENGTH LIMIT');
            const isUntranslated = decoded.toLowerCase() === text.trim().toLowerCase();
            
            if (!isWarning && !isUntranslated && decoded.length > 0) {
              return decoded;
            }
          }
        }
      } catch (err) {
        if (err.name === 'AbortError' && signal && signal.aborted) {
          throw err;
        }
      }
      // If MyMemory failed, timed out, or returned invalid/untranslated text:
      // Silently fall back to Google Translate!
    }

    // Google Translate Primary: gtx
    try {
      const gtxUrl = `https://translate.googleapis.com/translate_a/single?client=gtx&sl=${encodeURIComponent(sl)}&tl=${encodeURIComponent(tl)}&dt=t&q=${encodeURIComponent(text)}`;
      const res = await fetch(gtxUrl, { method: 'GET', signal, keepalive: true });
      if (res.ok) {
        const data = await res.json();
        if (Array.isArray(data) && Array.isArray(data[0])) {
          const translated = data[0]
            .map((item) => (Array.isArray(item) && item[0] ? item[0] : ''))
            .join('');
          if (translated) {
            return decodeHtmlEntities(translated);
          }
        }
      }
    } catch (e) {
      if (e.name === 'AbortError') throw e;
    }

    // Google Translate Backup: clients5
    try {
      const backupUrl = `https://clients5.google.com/translate_a/t?client=dict-chrome-ex&sl=${encodeURIComponent(sl)}&tl=${encodeURIComponent(tl)}&q=${encodeURIComponent(text)}`;
      const backupRes = await fetch(backupUrl, { method: 'GET', signal, keepalive: true });
      if (backupRes.ok) {
        const backupData = await backupRes.json();
        const result = Array.isArray(backupData) ? backupData[0] : backupData;
        if (result && typeof result === 'string' && result.trim()) {
          return decodeHtmlEntities(result.trim());
        }
      }
    } catch (e) {
      if (e.name === 'AbortError') throw e;
    }

    throw new Error('All direct translation endpoints failed');
  }

  /**
   * High-speed translation with local synchronous cache & request deduplication
   */
  async function translateTextFast(text) {
    const trimmed = normalizeText(text);
    if (!trimmed) return '';

    const service = getEffectiveService();
    const cacheKey = getCacheKey(service, settings.sourceLang, settings.targetLang, trimmed);

    // 1. Check local synchronous cache (0ms instant return!)
    if (localCache.has(cacheKey)) {
      return localCache.get(cacheKey);
    }
    // Also check mirror key for gemini
    if (localCache.has(getCacheKey('gemini', settings.sourceLang, settings.targetLang, trimmed))) {
      return localCache.get(getCacheKey('gemini', settings.sourceLang, settings.targetLang, trimmed));
    }

    // 1.1 Check native pre-translated cues from YouTube
    if (nativeTranslationsByText.has(trimmed)) {
      const nativeTrans = nativeTranslationsByText.get(trimmed);
      localCache.set(cacheKey, nativeTrans);
      return nativeTrans;
    }

    // 1.2 If Gemini engine is active but bypass condition met (YouTube auto-translate / ASR / already target lang):
    if (service === 'gemini' && shouldBypassGemini(trimmed)) {
      if (isAlreadyTargetLanguage(trimmed, settings.targetLang)) {
        localCache.set(cacheKey, trimmed);
        return trimmed;
      }
      // Use free fast Google Translate endpoint instead of Gemini to save user quota & avoid spamming
      try {
        const fallbackTrans = await fetchDirectTranslation(
          trimmed,
          settings.sourceLang || 'auto',
          settings.targetLang || 'vi',
          'google',
          null
        );
        if (fallbackTrans) {
          localCache.set(cacheKey, fallbackTrans);
          chrome.runtime.sendMessage({ action: 'RECORD_QUOTA_SAVED', count: 1 }).catch(() => {});
          return fallbackTrans;
        }
      } catch (_) {}
    }

    // 2. Deduplicate in-flight requests for identical text
    if (inFlightTranslations.has(cacheKey)) {
      return inFlightTranslations.get(cacheKey);
    }

    const promise = (async () => {
      let translated = '';

      // Direct fetch / background service worker
      try {
        const effectiveApiKey = service === 'gemini'
          ? (settings.geminiApiKey || '')
          : (settings.customApiKey || '');

        const effectivePronoun = currentSongPronounRole !== 'auto'
          ? currentSongPronounRole
          : (settings.geminiPronounRole || 'auto');

        const response = await chrome.runtime.sendMessage({
          action: 'TRANSLATE',
          text: trimmed,
          sourceLang: settings.sourceLang || 'auto',
          targetLang: settings.targetLang || 'vi',
          service: service,
          apiKey: effectiveApiKey,
          model: settings.geminiModel || 'gemini-3.5-flash-lite',
          videoTitle: getVideoContext(),
          style: settings.geminiStyle || 'auto',
          pronounRole: effectivePronoun,
          contextTail: getSmartContextTail(lastTranslatedTail, 2),
        });

        if (response && response.success && response.translation) {
          translated = response.translation;
          updateSongPronounRoleFromTranslations(translated);
          lastTranslatedTail = [...lastTranslatedTail, { original: trimmed, translation: translated }].slice(-10);
        }
      } catch (err) {
        console.warn('[YT ViSub] Translation message failed:', err);
      }

      // If Gemini translation failed or was empty, auto-fallback to Google Translate fast endpoint
      if (!translated && service === 'gemini') {
        try {
          translated = await fetchDirectTranslation(
            trimmed,
            settings.sourceLang || 'auto',
            settings.targetLang || 'vi',
            'google',
            null
          );
        } catch (_) {}
      }

      // Store in local cache (only genuine non-empty translations)
      if (translated && translated.trim().toLowerCase() !== trimmed.toLowerCase()) {
        if (localCache.size >= MAX_LOCAL_CACHE) {
          const firstKey = localCache.keys().next().value;
          localCache.delete(firstKey);
        }
        localCache.set(cacheKey, translated);
        localCache.set(getCacheKey('gemini', settings.sourceLang, settings.targetLang, trimmed), translated);
      }

      return translated || '';
    })();

    inFlightTranslations.set(cacheKey, promise);
    try {
      return await promise;
    } finally {
      inFlightTranslations.delete(cacheKey);
    }
  }

  /**
   * Extract current subtitle text from YouTube DOM
   */
  function extractCaptionText() {
    if (!playerElement) return '';

    const captionContainer = playerElement.querySelector('.ytp-caption-window-container');
    if (!captionContainer) return '';

    const segments = captionContainer.querySelectorAll('.ytp-caption-segment');
    if (!segments || segments.length === 0) return '';

    const lines = [];
    segments.forEach((seg) => {
      const text = seg.textContent ? seg.textContent.trim() : '';
      if (text) {
        lines.push(text);
      }
    });

    return normalizeText(lines.join(' '));
  }

  /**
   * Find subtitle cue at specific video timestamp
   */
  function getCurrentCueAtTime(timeMs) {
    if (!videoTimedCues || videoTimedCues.length === 0) return null;
    return videoTimedCues.find((c) => timeMs >= c.startMs && timeMs <= c.startMs + c.durMs + 400) || null;
  }

  /**
   * Render original subtitle immediately with a loading indicator beneath it.
   * Ensures subtitle is never blank or delayed while AI/service is translating.
   */
  function renderSubtitleWithLoading(origText) {
    if (!innerBox || !origText) return;

    if (originalTextElement) {
      originalTextElement.textContent = origText;
    }
    if (origWrapper) {
      origWrapper.style.display = 'block';
    }

    if (translatedTextElement) {
      translatedTextElement.innerHTML = '<span class="ytsub-loading-line">Đang dịch<span class="ytsub-loading-dots">...</span></span>';
    }
    if (transWrapper) {
      transWrapper.style.display = 'block';
    }

    innerBox.classList.remove('ytsub-hidden');
  }

  /**
   * Render subtitle lines simultaneously (Guarantees atomic parallel display - song song cùng lúc)
   */
  function renderSubtitlesSimultaneously(origText, transText) {
    if (!innerBox) return;

    if (!transText) {
      if (origText) {
        renderSubtitleWithLoading(origText);
      } else {
        innerBox.classList.add('ytsub-hidden');
      }
      return;
    }

    if (settings.displayMode === 'bilingual') {
      if (originalTextElement) originalTextElement.textContent = origText || '';
      if (origWrapper) origWrapper.style.display = origText ? 'block' : 'none';
    } else {
      if (origWrapper) origWrapper.style.display = 'none';
    }

    if (translatedTextElement) {
      translatedTextElement.innerHTML = '';
      translatedTextElement.textContent = transText;
    }
    if (transWrapper) {
      transWrapper.style.display = 'block';
    }

    innerBox.classList.remove('ytsub-hidden');
  }

  /**
   * Process subtitle updates:
   * Guarantees that original and translated subtitle ALWAYS appear at the exact same instant (song song).
   */
  async function onCaptionsChanged() {
    if (!settings.enabled || settings.displayMode === 'off') {
      if (innerBox && !innerBox.classList.contains('ytsub-hidden')) {
        innerBox.classList.add('ytsub-hidden');
      }
      return;
    }

    const currentText = extractCaptionText();

    if (!currentText) {
      lastCaptionText = '';
      if (innerBox && !innerBox.classList.contains('ytsub-hidden')) {
        innerBox.classList.add('ytsub-hidden');
        if (originalTextElement) originalTextElement.textContent = '';
        if (translatedTextElement) translatedTextElement.textContent = '';
      }
      return;
    }

    if (currentText === lastCaptionText) {
      return;
    }

    // Sync font size if in fullscreen and native caption size changed or became available
    if (isPlayerFullscreen() && (settings.fullscreenScaleMode || 'sync_yt') === 'sync_yt') {
      const newFs = computeEffectiveFontSize();
      if (Math.abs(newFs - lastAppliedFontSize) >= 1) {
        applySettings();
      }
    }

    // 0. If subtitle already matches target language (e.g. video has Vietnamese captions):
    // Display YouTube's native subtitle directly, DO NOT call 3rd-party/Gemini, DO NOT show duplicate lines!
    if (isTrackMatchingTargetLanguage(currentText)) {
      lastCaptionText = currentText;
      updateNativeSubtitleVisibility(true);
      return;
    }

    // Foreign subtitle: Show custom translator overlay
    updateNativeSubtitleVisibility(false);

    if (currentText === lastCaptionText) {
      return;
    }

    lastCaptionText = currentText;

    const service = getEffectiveService();
    const cacheKey = getCacheKey(service, settings.sourceLang, settings.targetLang, currentText);

    // 0. Offline Sound & Action Cue Interceptor (0ms, 0 API Quota consumed!)
    const soundOffline = resolveSoundCueOffline(currentText);
    if (soundOffline) {
      localCache.set(cacheKey, soundOffline);
      renderSubtitlesSimultaneously(currentText, soundOffline);
      chrome.runtime.sendMessage({ action: 'RECORD_QUOTA_SAVED', count: 1 }).catch(() => {});
      return;
    }

    // 1. Check local synchronous cache (0ms instant return - atomic simultaneous display)
    const cached = localCache.get(cacheKey) || (service !== 'gemini' ? localCache.get(getCacheKey('gemini', settings.sourceLang, settings.targetLang, currentText)) : null);

    if (cached) {
      renderSubtitlesSimultaneously(currentText, cached);
      return;
    }

    // 1.1 Check native pre-translated cues from YouTube (Only for non-Gemini services)
    if (service !== 'gemini' && nativeTranslationsByText.has(currentText)) {
      const nativeTrans = nativeTranslationsByText.get(currentText);
      localCache.set(cacheKey, nativeTrans);
      renderSubtitlesSimultaneously(currentText, nativeTrans);
      chrome.runtime.sendMessage({ action: 'RECORD_QUOTA_SAVED', count: 1 }).catch(() => {});
      return;
    }

    // 2. If not cached yet (e.g. at 1s, 5s or right after seeking):
    // IMMEDIATELY render original subtitle with loading line below it, never blank!
    renderSubtitleWithLoading(currentText);

    // Instantly trigger lookahead cluster pre-translation for upcoming cues!
    prioritizeUpcomingClusters();

    // 3. Fetch primary translation and render seamlessly

    // 4. Fetch primary translation (Gemini AI) and upgrade seamlessly
    const result = await translateTextFast(currentText);

    if (result) {
      const activeText = extractCaptionText();
      // Render if still on this caption or if active caption is continuing this phrase
      if (activeText === currentText || (activeText && activeText.startsWith(currentText)) || currentText === lastCaptionText) {
        const isDuplicate = result.trim().toLowerCase() === currentText.trim().toLowerCase() && detectScriptLanguage(currentText);
        const safeTrans = isDuplicate ? '' : result;
        if (safeTrans) {
          renderSubtitlesSimultaneously(activeText || currentText, safeTrans);
        }
      }
    }
  }

  /**
   * Parse timedtext data (JSON3 or XML) received from inject.js
   * Returns array of cues: [{ startMs, durMs, text }]
   */
  function parseTimedTextData(data) {
    const cues = [];
    if (!data || typeof data !== 'string') return cues;

    if (data.trim().startsWith('{')) {
      try {
        const json = JSON.parse(data);
        if (json.events && Array.isArray(json.events)) {
          json.events.forEach((e) => {
            if (e.segs) {
              const text = e.segs.map((s) => s.utf8 || '').join('').trim();
              const cleaned = normalizeText(text);
              if (cleaned && cleaned.length > 1) {
                const startMs = typeof e.tStartMs === 'number' ? e.tStartMs : 0;
                const durMs = typeof e.dDurationMs === 'number' ? e.dDurationMs : 2000;
                cues.push({ startMs, durMs, text: cleaned });
              }
            }
          });
        }
      } catch (e) {}
    }

    if (cues.length === 0 && data.includes('<text')) {
      const regex = /<text\s+start="([^"]*)"\s+dur="([^"]*)"[^>]*>([\s\S]*?)<\/text>/g;
      let match;
      while ((match = regex.exec(data)) !== null) {
        const startSec = parseFloat(match[1]) || 0;
        const durSec = parseFloat(match[2]) || 2;
        const cleaned = normalizeText(decodeHtmlEntities(match[3].replace(/<[^>]+>/g, '')));
        if (cleaned && cleaned.length > 1) {
          cues.push({
            startMs: Math.floor(startSec * 1000),
            durMs: Math.floor(durSec * 1000),
            text: cleaned,
          });
        }
      }
    }

    cues.sort((a, b) => a.startMs - b.startMs);
    return cues;
  }

  let lastGeminiBatchTime = 0;

  /**
   * Schedule intelligent full-video background pre-translation.
   * Multi-tier priority ensures that the immediate playback cluster is translated first,
   * while all remaining cues across the entire video (forward & past) continue translating
   * steadily in the background without stalling, while strictly respecting 15 RPM limits.
   */
  function scheduleFullVideoPretranslation(targetTimeMs = null) {
    if (!videoTimedCues || videoTimedCues.length === 0) return;
    const currentMs = targetTimeMs !== null ? targetTimeMs : getVideoCurrentTimeMs();

    const service = getEffectiveService();
    const sl = settings.sourceLang || 'auto';
    const tl = settings.targetLang || 'vi';

    // If subtitle language matches target language or YouTube is auto-translating, skip pre-translation
    if (isYouTubeAutoTranslateActive || isTrackMatchingTargetLanguage()) {
      return;
    }

    // 0. Auto-resolve all sound/action cues directly into localCache offline (0ms, 0 API Quota)
    let soundResolvedCount = 0;
    videoTimedCues.forEach((c) => {
      const sound = resolveSoundCueOffline(c.text);
      if (sound) {
        const key = getCacheKey(service, sl, tl, c.text);
        if (!localCache.has(key)) {
          localCache.set(key, sound);
          soundResolvedCount++;
        }
      }
    });
    if (soundResolvedCount > 0) {
      chrome.runtime.sendMessage({ action: 'RECORD_QUOTA_SAVED', count: soundResolvedCount }).catch(() => {});
    }

    // 1. Identify all uncached cues across the entire video
    const uncachedCues = videoTimedCues.filter((c) => {
      return !localCache.has(getCacheKey(service, sl, tl, c.text));
    });

    if (uncachedCues.length === 0) {
      pretranslateQueue = [];
      return;
    }

    // 2. Multi-tier priority ordering:
    // Tier 1: Immediate upcoming window [currentMs - 2s, currentMs + 60s]
    // Tier 2: Downstream upcoming [currentMs + 60s -> end of video]
    // Tier 3: Upstream past cues [0 -> currentMs - 2s] (so seeking backwards is already cached!)
    const tier1 = [];
    const tier2 = [];
    const tier3 = [];

    uncachedCues.forEach((c) => {
      if (c.startMs >= Math.max(0, currentMs - 2000) && c.startMs <= currentMs + 60000) {
        tier1.push(c.text);
      } else if (c.startMs > currentMs + 60000) {
        tier2.push(c.text);
      } else {
        tier3.push(c.text);
      }
    });

    // Deduplicate preserving strict priority order
    const ordered = [...tier1, ...tier2, ...tier3];
    const uniqueQueue = [];
    const seen = new Set();
    for (const txt of ordered) {
      if (!seen.has(txt)) {
        seen.add(txt);
        uniqueQueue.push(txt);
      }
    }

    pretranslateQueue = uniqueQueue;
    processPretranslationQueue();
  }

  // Alias for backward-compatible call sites
  function prioritizeUpcomingClusters(targetTimeMs = null) {
    scheduleFullVideoPretranslation(targetTimeMs);
  }

  /**
   * Parse pre-translated JSON3 from YouTube Native Translation (&tlang=)
   */
  function parseYouTubeNativeTranslatedData(data) {
    if (!data || typeof data !== 'string' || !data.trim().startsWith('{')) return;
    try {
      const json = JSON.parse(data);
      if (json.events && Array.isArray(json.events)) {
        const sl = settings.sourceLang || 'auto';
        const tl = settings.targetLang || 'vi';
        let countLoaded = 0;

        json.events.forEach((e) => {
          if (e.segs) {
            const transText = normalizeText(e.segs.map((s) => s.utf8 || '').join(''));
            if (transText && transText.length > 0) {
              const startMs = typeof e.tStartMs === 'number' ? e.tStartMs : 0;
              nativeTranslationsByMs.set(startMs, transText);

              // Cache transText -> transText so we never re-translate already translated subtitles
              if (settings.translationService !== 'gemini') {
                localCache.set(getCacheKey(settings.translationService, sl, tl, transText), transText);
                localCache.set(getCacheKey('gemini', sl, tl, transText), transText);
              }
              countLoaded++;
            }
          }
        });

        // If chronological cues are already available, match and cache them immediately
        if (videoTimedCues && videoTimedCues.length > 0) {
          matchTimedCuesWithNativeTranslations(videoTimedCues);
        }

        console.log(`[YT ViSub] YouTube Native pre-translated cues processed (${countLoaded} cues).`);
      }
    } catch (e) {
      console.warn('[YT ViSub] Failed to parse YouTube native translated data:', e);
    }
  }

  /**
   * Pre-translate batches of sentences steadily in the background across the whole video
   * Strictly respects rate limits (15 RPM for Gemini free tier) while ensuring full video coverage
   */
  async function processPretranslationQueue() {
    if (isPretranslating || pretranslateQueue.length === 0) return;
    if (isTrackMatchingTargetLanguage()) {
      pretranslateQueue = [];
      return;
    }
    isPretranslating = true;

    const service = getEffectiveService();
    const sl = settings.sourceLang || 'auto';
    const tl = settings.targetLang || 'vi';

    try {
      if (service === 'gemini' && settings.geminiApiKey) {
        // If YouTube auto-translate or ASR is active, skip Gemini batch calls completely to save quota
        if (shouldBypassGemini()) {
          console.log('[YT ViSub] YouTube auto-translate or ASR active. Skipping Gemini batch pre-translation to save user quota.');
          pretranslateQueue = [];
          return;
        }

        // High-density batch: 12-22 lines per request (compact, high-speed, genre-aware)
        const currentContext = getVideoContext();
        const currentStyle = settings.geminiStyle || 'auto';
        const currentPronoun = settings.geminiPronounRole || 'auto';

        while (pretranslateQueue.length > 0 && settings.translationService === 'gemini') {
          // If auto-translate detected mid-stream, immediately stop Gemini
          if (shouldBypassGemini()) {
            pretranslateQueue = [];
            break;
          }
          // 1. Pacing rate-limiter: Enforce at least 3.8s between Gemini calls to guarantee <= 15 RPM
          const now = Date.now();
          const elapsed = now - lastGeminiBatchTime;
          const minInterval = 3800; // 3.8s guarantees staying strictly under 15 RPM
          if (elapsed < minInterval && lastGeminiBatchTime > 0) {
            await new Promise((r) => setTimeout(r, minInterval - elapsed));
          }

          if (settings.translationService !== 'gemini') break;

          // Mega-Batch sizing: If remaining queue has <= 40 cues (e.g. whole song), take all in 1 single request!
          // Otherwise, pack up to 32 cues per batch to minimize total requests to the absolute minimum!
          let batchSize = pretranslateQueue.length <= 40 ? pretranslateQueue.length : 32;

          // Semantic boundary check: if batching partially, look for a sentence end (. ? ! ♪) around 24-32
          if (pretranslateQueue.length > 40 && batchSize === 32) {
            for (let i = 31; i >= 24; i--) {
              const cueText = pretranslateQueue[i] || '';
              if (/[\.\?\!♪♫\n]$/.test(cueText.trim()) || cueText.length < 15) {
                batchSize = i + 1;
                break;
              }
            }
          }

          const batch = pretranslateQueue.splice(0, batchSize);
          const toTranslate = batch.filter((txt) => !localCache.has(getCacheKey(service, sl, tl, txt)));
          if (toTranslate.length === 0) continue;

          lastGeminiBatchTime = Date.now();

          try {
            const effectivePronoun = currentSongPronounRole !== 'auto'
              ? currentSongPronounRole
              : currentPronoun;

            const response = await chrome.runtime.sendMessage({
              action: 'TRANSLATE_BATCH_GEMINI',
              lines: toTranslate,
              sourceLang: sl,
              targetLang: tl,
              apiKey: settings.geminiApiKey,
              model: settings.geminiModel || 'gemini-3.5-flash-lite',
              videoTitle: currentContext,
              style: currentStyle,
              pronounRole: effectivePronoun,
              contextTail: getSmartContextTail(lastTranslatedTail, 2),
            });

            if (response && response.success && Array.isArray(response.translations)) {
              updateSongPronounRoleFromTranslations(response.translations);
              const newTail = [];
              toTranslate.forEach((orig, idx) => {
                const trans = (response.translations[idx] || '').trim();
                if (trans) {
                  localCache.set(getCacheKey(service, sl, tl, orig), trans);
                  newTail.push({ original: orig, translation: trans });
                }
              });
              if (newTail.length > 0) {
                lastTranslatedTail = [...lastTranslatedTail, ...newTail].slice(-10);
              }
              console.log(`[YT ViSub] [Gemini Full-Video] Translated ${toTranslate.length} cues into cache. Remaining in queue: ${pretranslateQueue.length}`);
            } else if (response && response.error && response.error.includes('429')) {
              // Rate limit hit: backoff for 6 seconds, requeue items at front
              console.warn('[YT ViSub] Gemini rate limit reached (429), pausing background worker for 6s...');
              pretranslateQueue.unshift(...toTranslate);
              await new Promise((r) => setTimeout(r, 6000));
            }
          } catch (e) {
            console.warn('[YT ViSub] Gemini batch pre-translation failed:', e);
          }
        }
      } else if (service === 'google') {
        // Batch pre-translation with Google Translate (25 lines per request)
        while (pretranslateQueue.length > 0 && getEffectiveService() === 'google') {
          const batch = pretranslateQueue.splice(0, 25);
          const toTranslate = batch.filter((txt) => !localCache.has(getCacheKey(service, sl, tl, txt)));
          if (toTranslate.length === 0) continue;

          try {
            const combinedQuery = toTranslate.join('\n');
            const url = `https://translate.googleapis.com/translate_a/single?client=gtx&sl=${encodeURIComponent(sl)}&tl=${encodeURIComponent(tl)}&dt=t&q=${encodeURIComponent(combinedQuery)}`;

            const res = await fetch(url, { keepalive: true });
            if (res.ok) {
              const json = await res.json();
              if (Array.isArray(json) && Array.isArray(json[0])) {
                const translatedFull = json[0].map((item) => (Array.isArray(item) && item[0] ? item[0] : '')).join('');
                const translatedLines = decodeHtmlEntities(translatedFull).split('\n');

                toTranslate.forEach((orig, idx) => {
                  const trans = (translatedLines[idx] || '').trim();
                  if (trans) {
                    localCache.set(getCacheKey(service, sl, tl, orig), trans);
                    localCache.set(getCacheKey('gemini', sl, tl, orig), trans);
                  }
                });
              }
            }
          } catch (e) {}

          await new Promise((r) => setTimeout(r, 150));
        }
      }
    } finally {
      isPretranslating = false;
      // If there are still uncached cues anywhere in the video, resume background cruising
      if (videoTimedCues && videoTimedCues.length > 0) {
        const hasUncached = videoTimedCues.some((c) => !localCache.has(getCacheKey(service, sl, tl, c.text)));
        if (hasUncached && pretranslateQueue.length > 0) {
          processPretranslationQueue();
        }
      }
    }
  }

  /**
   * Listen for intercepted timedtext subtitles from inject.js
   */
  window.addEventListener('message', (event) => {
    if (!event.data || event.data.source !== 'YTSUB_INJECT') return;

    if (event.data.type === 'CAPTION_TRACK_STATUS') {
      if (typeof event.data.isAutoTranslate === 'boolean') {
        isYouTubeAutoTranslateActive = event.data.isAutoTranslate;
      }
      if (typeof event.data.isAutoGenerated === 'boolean') {
        isAutoGeneratedTrack = event.data.isAutoGenerated;
      }
      if (event.data.trackLang) {
        detectedCaptionLang = event.data.trackLang;
      }
      if (isTrackMatchingTargetLanguage()) {
        updateNativeSubtitleVisibility(true);
      } else {
        updateNativeSubtitleVisibility(false);
      }
      return;
    }

    if (event.data.captionLang) {
      detectedCaptionLang = event.data.captionLang;
      if (isTrackMatchingTargetLanguage()) {
        updateNativeSubtitleVisibility(true);
      }
    }
    if (event.data.isAutoTranslate) {
      isYouTubeAutoTranslateActive = true;
    }
    if (event.data.isAutoGenerated) {
      isAutoGeneratedTrack = true;
    }

    if (event.data.type === 'TIMEDTEXT_TRANSLATED_RESPONSE') {
      parseYouTubeNativeTranslatedData(event.data.data);
    } else if (event.data.type === 'TIMEDTEXT_RESPONSE') {
      const cues = parseTimedTextData(event.data.data);
      if (cues.length > 0) {
        videoTimedCues = cues;
        matchTimedCuesWithNativeTranslations(cues);
        console.log(`[YT ViSub] Loaded ${cues.length} chronological subtitle cues for cluster pre-translation.`);
        prioritizeUpcomingClusters();
      }
    }
  });

  let playerContainerObserver = null;

  /**
   * Attach MutationObserver to caption container exclusively.
   * Never attaches heavy subtree observers to playerElement to eliminate video lag.
   */
  function observeCaptionContainer() {
    if (captionObserver) {
      captionObserver.disconnect();
      captionObserver = null;
    }
    if (playerContainerObserver) {
      playerContainerObserver.disconnect();
      playerContainerObserver = null;
    }

    if (!playerElement) return;

    const captionContainer = playerElement.querySelector('.ytp-caption-window-container');
    if (!captionContainer) {
      // Shallow observe playerElement with childList: true only (no subtree, no characterData)
      // solely to detect when .ytp-caption-window-container is created by YouTube
      playerContainerObserver = new MutationObserver(() => {
        const found = playerElement.querySelector('.ytp-caption-window-container');
        if (found) {
          playerContainerObserver.disconnect();
          playerContainerObserver = null;
          observeCaptionContainer();
        }
      });
      playerContainerObserver.observe(playerElement, { childList: true });
      return;
    }

    captionObserver = new MutationObserver(() => {
      onCaptionsChanged();
    });

    captionObserver.observe(captionContainer, {
      childList: true,
      subtree: true,
      characterData: true,
    });

    onCaptionsChanged();
  }

  /**
   * Express Lane for Seek / Play:
   * Fast-tracks immediate 8 cues around seek point for ultra-low latency (~300ms)
   * while removing them from Cruise Lane to avoid duplicate API requests.
   */
  async function dispatchExpressCluster(targetTimeMs) {
    if (!videoTimedCues || videoTimedCues.length === 0) return;
    if (isTrackMatchingTargetLanguage()) return;
    const service = getEffectiveService();
    if (service !== 'gemini' || !settings.geminiApiKey) return;

    const sl = settings.sourceLang || 'auto';
    const tl = settings.targetLang || 'vi';

    // Immediate 8 cues in [targetTimeMs - 1000ms, targetTimeMs + 25000ms]
    const urgentCues = videoTimedCues
      .filter((c) => c.startMs >= Math.max(0, targetTimeMs - 1000) && c.startMs <= targetTimeMs + 25000)
      .map((c) => c.text)
      .filter((txt) => !localCache.has(getCacheKey(service, sl, tl, txt)));

    const uniqueUrgent = Array.from(new Set(urgentCues)).slice(0, 8);
    if (uniqueUrgent.length === 0) return;

    // Retrieve preceding cue before targetTimeMs as context tail for seamless seeking
    let expressTail = [];
    if (lastTranslatedTail && lastTranslatedTail.length > 0) {
      expressTail = getSmartContextTail(lastTranslatedTail, 2);
    } else {
      const priorCue = videoTimedCues
        .filter((c) => c.startMs < targetTimeMs)
        .slice(-1)[0];
      if (priorCue && priorCue.text) {
        const cachedPrior = localCache.get(getCacheKey(service, sl, tl, priorCue.text));
        if (cachedPrior) {
          expressTail = [{ original: priorCue.text, translation: cachedPrior }];
        }
      }
    }

    try {
      const effectivePronoun = currentSongPronounRole !== 'auto'
        ? currentSongPronounRole
        : (settings.geminiPronounRole || 'auto');

      const response = await chrome.runtime.sendMessage({
        action: 'TRANSLATE_BATCH_GEMINI',
        lines: uniqueUrgent,
        sourceLang: sl,
        targetLang: tl,
        apiKey: settings.geminiApiKey,
        model: settings.geminiModel || 'gemini-3.5-flash-lite',
        videoTitle: getVideoContext(),
        style: settings.geminiStyle || 'auto',
        pronounRole: effectivePronoun,
        contextTail: expressTail,
      });

      if (response && response.success && Array.isArray(response.translations)) {
        updateSongPronounRoleFromTranslations(response.translations);
        const newTail = [];
        uniqueUrgent.forEach((orig, idx) => {
          const trans = (response.translations[idx] || '').trim();
          if (trans) {
            localCache.set(getCacheKey(service, sl, tl, orig), trans);
            newTail.push({ original: orig, translation: trans });
          }
        });
        if (newTail.length > 0) {
          lastTranslatedTail = [...lastTranslatedTail, ...newTail].slice(-10);
        }

        // Upgrade active subtitle if it matches any translated cue
        const activeText = extractCaptionText();
        if (activeText && localCache.has(getCacheKey(service, sl, tl, activeText))) {
          renderSubtitlesSimultaneously(activeText, localCache.get(getCacheKey(service, sl, tl, activeText)));
        }
      }
    } catch (_) {}
  }

  function onVideoSeeked() {
    const currentMs = getVideoCurrentTimeMs();

    // 1. Reorganize full video background queue (Cruise Lane)
    prioritizeUpcomingClusters(currentMs);

    // 2. Dispatch Express Lane for immediate cues at the seek point
    dispatchExpressCluster(currentMs);

    if (!settings.enabled || settings.displayMode === 'off') return;

    const activeText = extractCaptionText();
    if (isTrackMatchingTargetLanguage(activeText)) {
      updateNativeSubtitleVisibility(true);
      return;
    }

    const service = getEffectiveService();

    if (activeText) {
      const soundOffline = resolveSoundCueOffline(activeText);
      const cacheKey = getCacheKey(service, settings.sourceLang, settings.targetLang, activeText);
      if (soundOffline) {
        localCache.set(cacheKey, soundOffline);
        renderSubtitlesSimultaneously(activeText, soundOffline);
        return;
      }
      const cached = localCache.get(cacheKey) || localCache.get(getCacheKey('gemini', settings.sourceLang, settings.targetLang, activeText));
      if (cached) {
        renderSubtitlesSimultaneously(activeText, cached);
      } else {
        renderSubtitleWithLoading(activeText);
      }
    } else {
      const cue = getCurrentCueAtTime(currentMs);
      if (cue && cue.text) {
        const soundOffline = resolveSoundCueOffline(cue.text);
        const cacheKey = getCacheKey(service, settings.sourceLang, settings.targetLang, cue.text);
        if (soundOffline) {
          localCache.set(cacheKey, soundOffline);
          renderSubtitlesSimultaneously(cue.text, soundOffline);
          return;
        }
        const cached = localCache.get(cacheKey) || localCache.get(getCacheKey('gemini', settings.sourceLang, settings.targetLang, cue.text));
        if (cached) {
          renderSubtitlesSimultaneously(cue.text, cached);
        } else {
          renderSubtitleWithLoading(cue.text);
        }
      }
    }
  }

  function onVideoPlay() {
    prioritizeUpcomingClusters();
  }

  function isWatchOrShortsPage() {
    const p = window.location.pathname;
    return p.startsWith('/watch') || p.startsWith('/shorts') || p.startsWith('/live');
  }

  /**
   * Initialize player
   */
  function initPlayer() {
    if (!isWatchOrShortsPage()) {
      if (overlayContainer) {
        overlayContainer.style.display = 'none';
      }
      if (playerElement) {
        playerElement.classList.remove('ytsub-hide-native');
      }
      return false;
    }

    const player = document.querySelector('#movie_player') || document.querySelector('.html5-video-player');
    if (!player) return false;

    playerElement = player;
    setupOverlay(player);
    observeCaptionContainer();
    syncConfigToMainWorld();

    const video = player.querySelector('video');
    if (video) {
      attachedVideoElement = video;
      video.removeEventListener('seeked', onVideoSeeked);
      video.addEventListener('seeked', onVideoSeeked);
      video.removeEventListener('play', onVideoPlay);
      video.addEventListener('play', onVideoPlay);
    }
    return true;
  }

  /**
   * Main initialization
   */
  function init() {
    loadSettings();

    // Listen to standard browser fullscreen and resize events (lightweight, zero thrashing)
    document.addEventListener('fullscreenchange', () => {
      cachedNativeFs = 0;
      applySettings();
      setTimeout(applySettings, 150);
    });
    document.addEventListener('webkitfullscreenchange', () => {
      cachedNativeFs = 0;
      applySettings();
      setTimeout(applySettings, 150);
    });

    let resizeTimer = null;
    window.addEventListener('resize', () => {
      clearTimeout(resizeTimer);
      resizeTimer = setTimeout(() => {
        cachedNativeFs = 0;
        applySettings();
      }, 200);
    });

    if (isWatchOrShortsPage()) {
      if (!initPlayer()) {
        let attempts = 0;
        const interval = setInterval(() => {
          attempts++;
          if (initPlayer() || attempts >= 10 || !isWatchOrShortsPage()) {
            clearInterval(interval);
          }
        }, 300);
      }
    }

    // YouTube SPA navigation events
    window.addEventListener('yt-navigate-finish', () => {
      lastCaptionText = '';
      detectedCaptionLang = '';
      isYouTubeAutoTranslateActive = false;
      isAutoGeneratedTrack = false;
      nativeTranslationsByMs.clear();
      nativeTranslationsByText.clear();
      videoTimedCues = [];
      pretranslateQueue = [];
      lastTranslatedTail = [];
      currentSongPronounRole = 'auto';
      cachedNativeFs = 0;
      if (playerElement) {
        playerElement.classList.remove('ytsub-hide-native');
      }
      if (isWatchOrShortsPage()) {
        setTimeout(() => initPlayer(), 150);
      }
    });

    window.addEventListener('spfdone', () => {
      lastCaptionText = '';
      detectedCaptionLang = '';
      isYouTubeAutoTranslateActive = false;
      isAutoGeneratedTrack = false;
      nativeTranslationsByMs.clear();
      nativeTranslationsByText.clear();
      videoTimedCues = [];
      pretranslateQueue = [];
      lastTranslatedTail = [];
      currentSongPronounRole = 'auto';
      cachedNativeFs = 0;
      if (playerElement) {
        playerElement.classList.remove('ytsub-hide-native');
      }
      if (isWatchOrShortsPage()) {
        setTimeout(() => initPlayer(), 150);
      }
    });
  }

  chrome.storage.onChanged.addListener((changes, namespace) => {
    if (namespace === 'sync' || namespace === 'local') {
      let serviceOrKeyChanged = false;
      for (const [key, change] of Object.entries(changes)) {
        settings[key] = change.newValue;
        if (key === 'translationService' || key === 'geminiApiKey' || key === 'geminiModel' || key === 'geminiStyle' || key === 'geminiPronounRole') {
          serviceOrKeyChanged = true;
        }
      }
      if (serviceOrKeyChanged) {
        localCache.clear();
        currentSongPronounRole = 'auto';
        console.log('[YT ViSub] Service or key updated. Local cache cleared. Active service:', settings.translationService);
      }
      applySettings();
      syncConfigToMainWorld();
      if (lastCaptionText) {
        lastCaptionText = '';
        onCaptionsChanged();
      }
    }
  });

  chrome.runtime.onMessage.addListener((request) => {
    if (request && request.action === 'CLEAR_LOCAL_CACHE') {
      localCache.clear();
      lastCaptionText = '';
      lastTranslatedTail = [];
      currentSongPronounRole = 'auto';
      console.log('[YT ViSub] Local memory cache cleared.');
      onCaptionsChanged();
    }
  });

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();
