/**
 * YouTube Subtitle Translator - Main World Interceptor (inject.js)
 * Intercepts YouTube's timedtext subtitle tracks and supports YouTube's Native Subtitle Translation engine (&tlang=).
 */

(() => {
  'use strict';

  if (window.__ytsub_injected) return;
  window.__ytsub_injected = true;

  let currentTargetLang = 'vi';
  let currentService = 'google';
  let lastFetchedUrl = '';

  // Receive active configuration from content.js
  window.addEventListener('message', (event) => {
    if (event.data && event.data.source === 'YTSUB_CONTENT_CONFIG') {
      if (event.data.targetLang) currentTargetLang = event.data.targetLang;
      if (event.data.service) currentService = event.data.service;
    }
  });

  function getVideoId(url) {
    try {
      if (url) {
        const match = url.match(/[?&]v=([a-zA-Z0-9_-]+)/);
        if (match && match[1]) return match[1];
      }
      const locMatch = window.location.search.match(/[?&]v=([a-zA-Z0-9_-]+)/);
      if (locMatch && locMatch[1]) return locMatch[1];
      const shortsMatch = window.location.pathname.match(/\/shorts\/([a-zA-Z0-9_-]+)/);
      if (shortsMatch && shortsMatch[1]) return shortsMatch[1];
      const liveMatch = window.location.pathname.match(/\/live\/([a-zA-Z0-9_-]+)/);
      if (liveMatch) return liveMatch[1];
    } catch (_) {}
    return '';
  }

  function notifySubtitleData(url, text, isTranslated = false, explicitLang = '', explicitTlang = '', explicitIsAsr = false, isPrefetch = false) {
    if (!text || text.length < 20) return;
    let captionLang = explicitLang;
    if (!captionLang && url) {
      try {
        const match = url.match(/[?&]lang=([a-zA-Z-]+)/);
        if (match && match[1]) {
          captionLang = match[1];
        }
      } catch (e) {}
    }

    let tlang = explicitTlang;
    if (!tlang && url) {
      try {
        const matchTlang = url.match(/[?&]tlang=([a-zA-Z-]+)/);
        if (matchTlang && matchTlang[1]) {
          tlang = matchTlang[1];
        }
      } catch (e) {}
    }

    const isAsr = explicitIsAsr || Boolean(url && url.includes('kind=asr'));
    const isAutoTrans = isTranslated || Boolean(tlang);
    const videoId = getVideoId(url);

    window.postMessage({
      source: 'YTSUB_INJECT',
      type: isAutoTrans ? 'TIMEDTEXT_TRANSLATED_RESPONSE' : 'TIMEDTEXT_RESPONSE',
      url: url,
      data: text,
      targetLang: currentTargetLang,
      captionLang: captionLang,
      tlang: tlang,
      isAutoTranslate: isAutoTrans,
      isAutoGenerated: isAsr,
      isPrefetch: Boolean(isPrefetch),
      videoId: videoId,
    }, '*');
  }

  // 1. Intercept XMLHttpRequest cleanly without altering prototype signatures
  const origOpen = XMLHttpRequest.prototype.open;
  const origSend = XMLHttpRequest.prototype.send;

  XMLHttpRequest.prototype.open = function(method, url) {
    this._ytsub_url = url;
    return origOpen.apply(this, arguments);
  };
  XMLHttpRequest.prototype.open.toString = function() {
    return origOpen.toString();
  };

  XMLHttpRequest.prototype.send = function() {
    if (this._ytsub_url && typeof this._ytsub_url === 'string' && this._ytsub_url.includes('/api/timedtext')) {
      const targetUrl = this._ytsub_url;
      this.addEventListener('load', function() {
        try {
          if (this.responseText) {
            const hasTlang = targetUrl.includes('tlang=');
            const isAsr = targetUrl.includes('kind=asr');
            notifySubtitleData(targetUrl, this.responseText, hasTlang, '', '', isAsr);
          }
        } catch (e) {}
      });
    }
    return origSend.apply(this, arguments);
  };
  XMLHttpRequest.prototype.send.toString = function() {
    return origSend.toString();
  };

  // 2. Intercept window.fetch non-invasively (zero microtask latency for streaming media)
  const origFetch = window.fetch;
  window.fetch = function(...args) {
    const promise = origFetch.apply(this, args);
    try {
      const url = args[0] ? (typeof args[0] === 'string' ? args[0] : args[0].url) : '';
      if (url && typeof url === 'string' && url.includes('/api/timedtext')) {
        promise.then((response) => {
          try {
            const clone = response.clone();
            clone.text().then((text) => {
              const hasTlang = url.includes('tlang=');
              const isAsr = url.includes('kind=asr');
              notifySubtitleData(url, text, hasTlang, '', '', isAsr);
            }).catch(() => {});
          } catch (_) {}
        }).catch(() => {});
      }
    } catch (_) {}
    return promise;
  };
  window.fetch.toString = function() {
    return origFetch.toString();
  };

  let lastTrackStatusKey = '';

  function isVideoPage() {
    const path = window.location.pathname;
    return path.startsWith('/watch') || path.startsWith('/shorts') || path.startsWith('/live');
  }

  function getTrackText(obj) {
    if (!obj) return '';
    if (typeof obj === 'string') return obj;
    if (typeof obj.simpleText === 'string') return obj.simpleText;
    if (Array.isArray(obj.runs)) return obj.runs.map((r) => r.text || '').join('');
    return '';
  }

  function isAsrTrack(track, target) {
    // 1. Direct kind / flag
    if (track && (track.kind === 'asr' || track.is_asr === true || track.isAsr === true)) return true;
    if (target && (target.kind === 'asr' || target.is_asr === true || target.isAsr === true)) return true;

    // 2. vssId check (YouTube auto-generated captions start with "a.")
    if (track && typeof track.vssId === 'string' && track.vssId.startsWith('a.')) return true;
    if (target && typeof target.vssId === 'string' && target.vssId.startsWith('a.')) return true;

    // 3. baseUrl query parameters
    if (target && typeof target.baseUrl === 'string' && target.baseUrl.includes('kind=asr')) return true;
    if (track && typeof track.baseUrl === 'string' && track.baseUrl.includes('kind=asr')) return true;

    // 4. Text title multi-language detection
    const names = [
      getTrackText(track?.name),
      getTrackText(track?.displayName),
      getTrackText(track?.languageName),
      getTrackText(target?.name),
      getTrackText(target?.displayName),
      getTrackText(target?.languageName),
    ].join(' ').toLowerCase();

    if (
      names.includes('được tạo tự động') ||
      names.includes('tự động tạo') ||
      names.includes('auto-generated') ||
      names.includes('generated automatically') ||
      names.includes('自動生成') ||
      names.includes('자동 생성') ||
      names.includes('automatisch') ||
      names.includes('automatiquement') ||
      names.includes('generado automáticamente') ||
      names.includes('создано автоматически')
    ) {
      return true;
    }

    return false;
  }

  // 3. Proactively fetch caption track (including YouTube Native Subtitle Translation)
  function inspectPlayerCaptions() {
    if (!isVideoPage()) return;

    try {
      const player = document.getElementById('movie_player') || document.querySelector('.html5-video-player');
      if (!player || typeof player.getOption !== 'function') return;

      const currentVid = getVideoId();
      const track = player.getOption('captions', 'track');
      const tracklist = player.getOption('captions', 'tracklist');

      // Check if video has any caption tracks at all
      const hasAnyTracks = Boolean((tracklist && Array.isArray(tracklist) && tracklist.length > 0) || (track && track.languageCode));
      if (!hasAnyTracks) {
        if (lastTrackStatusKey !== 'none') {
          lastTrackStatusKey = 'none';
          window.postMessage({
            source: 'YTSUB_INJECT',
            type: 'CAPTION_TRACK_STATUS',
            hasCaptions: false,
            isAutoTranslate: false,
            isAutoGenerated: false,
            trackLang: '',
            translationLang: '',
            videoId: currentVid,
          }, '*');
        }
        return;
      }

      const target = (track && track.languageCode) ? track : (tracklist && tracklist[0]);

      // Detect auto-translate & auto-generated ASR tracks
      const isAutoTranslate = Boolean(
        (track && track.translationLanguage && track.translationLanguage.languageCode) ||
        (track && track.vssId && (track.vssId.includes('&tlang=') || track.vssId.includes('tlang='))) ||
        (target && target.baseUrl && target.baseUrl.includes('tlang='))
      );

      const isAsr = isAsrTrack(track, target);

      const trackLang = target?.languageCode || '';
      const translationLang = track?.translationLanguage?.languageCode ||
        (target?.baseUrl?.match(/[?&]tlang=([a-zA-Z-]+)/)?.[1] || '');

      // Broadcast active track state to content.js only when changed
      const trackStatusKey = `${currentVid}:${isAutoTranslate}:${isAsr}:${trackLang}:${translationLang}`;
      if (trackStatusKey !== lastTrackStatusKey) {
        lastTrackStatusKey = trackStatusKey;
        window.postMessage({
          source: 'YTSUB_INJECT',
          type: 'CAPTION_TRACK_STATUS',
          hasCaptions: true,
          isAutoTranslate: isAutoTranslate,
          isAutoGenerated: isAsr,
          trackLang: trackLang,
          translationLang: translationLang,
          videoId: currentVid,
        }, '*');
      }

      if (target && target.baseUrl) {
        const urlVid = getVideoId(target.baseUrl);
        if (urlVid && currentVid && urlVid !== currentVid) {
          // Stale track from previous video! Do not fetch!
          return;
        }

        const fetchKey = `${target.baseUrl}:${currentTargetLang}:${currentService}:${isAutoTranslate}:${currentVid}`;
        if (fetchKey === lastFetchedUrl) return;
        lastFetchedUrl = fetchKey;

        // 1. Always proactively fetch original transcript for cluster pre-translation
        const cleanBaseUrl = target.baseUrl.replace(/[?&]tlang=[^&]*/g, '');
        const sep = cleanBaseUrl.includes('?') ? '&' : '?';
        const origUrl = cleanBaseUrl.includes('fmt=json3') ? cleanBaseUrl : `${cleanBaseUrl}${sep}fmt=json3`;

        origFetch(origUrl)
          .then((r) => r.text())
          .then((origText) => {
            if (origText && (origText.includes('events') || origText.includes('<text'))) {
              notifySubtitleData(origUrl, origText, false, trackLang, '', isAsr);
            }
          })
          .catch(() => {});

        // 2. Proactively fetch YouTube Native pre-translated &tlang track
        // Ensures YouTube native translation is available, saving user Gemini quota
        const nativeUrl = `${cleanBaseUrl}${sep}tlang=${encodeURIComponent(currentTargetLang)}&fmt=json3`;
        origFetch(nativeUrl)
          .then((res) => res.text())
          .then((text) => {
            if (text && text.includes('events')) {
              notifySubtitleData(nativeUrl, text, true, trackLang, currentTargetLang, isAsr, true);
            }
          })
          .catch(() => {});
      }
    } catch (e) {}
  }

  function onPlayerStateChange(state) {
    // 1 = PLAYING (buffer is ready and frames are rendering smoothly)
    if (state === 1) {
      setTimeout(inspectPlayerCaptions, 400);
    }
  }

  function attachPlayerListeners() {
    try {
      const player = document.getElementById('movie_player') || document.querySelector('.html5-video-player');
      if (player && typeof player.addEventListener === 'function') {
        player.removeEventListener('onCaptionsTrackListChanged', inspectPlayerCaptions);
        player.addEventListener('onCaptionsTrackListChanged', inspectPlayerCaptions);
        player.removeEventListener('captionsChanged', inspectPlayerCaptions);
        player.addEventListener('captionsChanged', inspectPlayerCaptions);
        player.removeEventListener('onStateChange', onPlayerStateChange);
        player.addEventListener('onStateChange', onPlayerStateChange);
      }
    } catch (_) {}
  }

  window.addEventListener('yt-navigate-start', () => {
    lastFetchedUrl = '';
    lastTrackStatusKey = '';
    window.postMessage({
      source: 'YTSUB_INJECT',
      type: 'NAVIGATE_START',
      videoId: getVideoId(),
    }, '*');
  });

  window.addEventListener('yt-navigate-finish', () => {
    lastFetchedUrl = '';
    lastTrackStatusKey = '';
    if (isVideoPage()) {
      // Attach player listeners early, but DEFER proactive network inspection until video has started playing
      // or after 1800ms so initial video stream buffering (videoplayback) is 100% unhindered!
      setTimeout(attachPlayerListeners, 300);
      setTimeout(inspectPlayerCaptions, 1800);
    }
  });

  window.addEventListener('load', () => {
    if (isVideoPage()) {
      setTimeout(attachPlayerListeners, 500);
      setTimeout(inspectPlayerCaptions, 1800);
    }
  });

  setInterval(inspectPlayerCaptions, 3500);
})();
