/**
 * YouTube Subtitle Translator - Main World Interceptor (inject.js)
 * Intercepts YouTube's timedtext subtitle tracks and supports YouTube's Native Subtitle Translation engine (&tlang=).
 */

(() => {
  'use strict';

  if (window.__ytsub_injected) return;
  window.__ytsub_injected = true;

  let currentTargetLang = 'vi';
  let currentService = 'google';
  let lastFetchedUrl = '';

  // Receive active configuration from content.js
  window.addEventListener('message', (event) => {
    if (event.data && event.data.source === 'YTSUB_CONTENT_CONFIG') {
      if (event.data.targetLang) currentTargetLang = event.data.targetLang;
      if (event.data.service) currentService = event.data.service;
    }
  });

  function notifySubtitleData(url, text, isTranslated = false, explicitLang = '', explicitTlang = '', explicitIsAsr = false) {
    if (!text || text.length < 20) return;
    let captionLang = explicitLang;
    if (!captionLang && url) {
      try {
        const match = url.match(/[?&]lang=([a-zA-Z-]+)/);
        if (match && match[1]) {
          captionLang = match[1];
        }
      } catch (e) {}
    }

    let tlang = explicitTlang;
    if (!tlang && url) {
      try {
        const matchTlang = url.match(/[?&]tlang=([a-zA-Z-]+)/);
        if (matchTlang && matchTlang[1]) {
          tlang = matchTlang[1];
        }
      } catch (e) {}
    }

    const isAsr = explicitIsAsr || Boolean(url && url.includes('kind=asr'));
    const isAutoTrans = isTranslated || Boolean(tlang);

    window.postMessage({
      source: 'YTSUB_INJECT',
      type: isAutoTrans ? 'TIMEDTEXT_TRANSLATED_RESPONSE' : 'TIMEDTEXT_RESPONSE',
      url: url,
      data: text,
      targetLang: currentTargetLang,
      captionLang: captionLang,
      tlang: tlang,
      isAutoTranslate: isAutoTrans,
      isAutoGenerated: isAsr,
    }, '*');
  }

  // 1. Intercept XMLHttpRequest
  const origOpen = XMLHttpRequest.prototype.open;
  const origSend = XMLHttpRequest.prototype.send;

  XMLHttpRequest.prototype.open = function(method, url) {
    this._ytsub_url = url;
    return origOpen.apply(this, arguments);
  };

  XMLHttpRequest.prototype.send = function() {
    if (this._ytsub_url && typeof this._ytsub_url === 'string' && this._ytsub_url.includes('/api/timedtext')) {
      const targetUrl = this._ytsub_url;
      this.addEventListener('load', function() {
        try {
          if (this.responseText) {
            const hasTlang = targetUrl.includes('tlang=');
            const isAsr = targetUrl.includes('kind=asr');
            notifySubtitleData(targetUrl, this.responseText, hasTlang, '', '', isAsr);
          }
        } catch (e) {}
      });
    }
    return origSend.apply(this, arguments);
  };

  // 2. Intercept window.fetch
  const origFetch = window.fetch;
  window.fetch = async function(...args) {
    const response = await origFetch.apply(this, args);
    try {
      const url = args[0] ? (typeof args[0] === 'string' ? args[0] : args[0].url) : '';
      if (url && typeof url === 'string' && url.includes('/api/timedtext')) {
        const clone = response.clone();
        clone.text().then((text) => {
          const hasTlang = url.includes('tlang=');
          const isAsr = url.includes('kind=asr');
          notifySubtitleData(url, text, hasTlang, '', '', isAsr);
        }).catch(() => {});
      }
    } catch (e) {}
    return response;
  };

  let lastTrackStatusKey = '';

  function isVideoPage() {
    const path = window.location.pathname;
    return path.startsWith('/watch') || path.startsWith('/shorts') || path.startsWith('/live');
  }

  // 3. Proactively fetch caption track (including YouTube Native Subtitle Translation)
  function inspectPlayerCaptions() {
    if (!isVideoPage()) return;

    try {
      const player = document.getElementById('movie_player') || document.querySelector('.html5-video-player');
      if (!player || typeof player.getOption !== 'function') return;

      const track = player.getOption('captions', 'track');
      const tracklist = player.getOption('captions', 'tracklist');
      const target = track || (tracklist && tracklist[0]);

      // Detect auto-translate & auto-generated ASR tracks
      const isAutoTranslate = Boolean(
        (track && track.translationLanguage && track.translationLanguage.languageCode) ||
        (track && track.vssId && (track.vssId.includes('&tlang=') || track.vssId.includes('tlang='))) ||
        (target && target.baseUrl && target.baseUrl.includes('tlang='))
      );

      const isAsr = Boolean(
        (track && (track.kind === 'asr' || (track.vssId && track.vssId.startsWith('a.')))) ||
        (target && (target.kind === 'asr' || (target.vssId && target.vssId.startsWith('a.')))) ||
        (target && target.baseUrl && target.baseUrl.includes('kind=asr')) ||
        (track && (
          (typeof track.name === 'string' && (track.name.includes('được tạo tự động') || track.name.toLowerCase().includes('auto-generated') || track.name.includes('tự động tạo'))) ||
          (typeof track.displayName === 'string' && (track.displayName.includes('được tạo tự động') || track.displayName.toLowerCase().includes('auto-generated') || track.displayName.includes('tự động tạo'))) ||
          (typeof track.languageName === 'string' && (track.languageName.includes('được tạo tự động') || track.languageName.toLowerCase().includes('auto-generated') || track.languageName.includes('tự động tạo')))
        ))
      );

      const trackLang = target?.languageCode || '';
      const translationLang = track?.translationLanguage?.languageCode ||
        (target?.baseUrl?.match(/[?&]tlang=([a-zA-Z-]+)/)?.[1] || '');

      // Broadcast active track state to content.js only when changed
      const trackStatusKey = `${isAutoTranslate}:${isAsr}:${trackLang}:${translationLang}`;
      if (trackStatusKey !== lastTrackStatusKey) {
        lastTrackStatusKey = trackStatusKey;
        window.postMessage({
          source: 'YTSUB_INJECT',
          type: 'CAPTION_TRACK_STATUS',
          isAutoTranslate: isAutoTranslate,
          isAutoGenerated: isAsr,
          trackLang: trackLang,
          translationLang: translationLang,
        }, '*');
      }

      if (target && target.baseUrl) {
        const fetchKey = `${target.baseUrl}:${currentTargetLang}:${currentService}:${isAutoTranslate}`;
        if (fetchKey === lastFetchedUrl) return;
        lastFetchedUrl = fetchKey;

        // 1. Always proactively fetch original transcript for cluster pre-translation
        const cleanBaseUrl = target.baseUrl.replace(/[?&]tlang=[^&]*/g, '');
        const sep = cleanBaseUrl.includes('?') ? '&' : '?';
        const origUrl = cleanBaseUrl.includes('fmt=json3') ? cleanBaseUrl : `${cleanBaseUrl}${sep}fmt=json3`;

        origFetch(origUrl)
          .then((r) => r.text())
          .then((origText) => {
            if (origText && (origText.includes('events') || origText.includes('<text'))) {
              notifySubtitleData(origUrl, origText, false, trackLang, '', isAsr);
            }
          })
          .catch(() => {});

        // 2. Proactively fetch YouTube Native pre-translated &tlang track
        // Ensures YouTube native translation is available, saving user Gemini quota
        const nativeUrl = `${cleanBaseUrl}${sep}tlang=${encodeURIComponent(currentTargetLang)}&fmt=json3`;
        origFetch(nativeUrl)
          .then((res) => res.text())
          .then((text) => {
            if (text && text.includes('events')) {
              notifySubtitleData(nativeUrl, text, true, trackLang, currentTargetLang, isAsr);
            }
          })
          .catch(() => {});
      }
    } catch (e) {}
  }

  window.addEventListener('yt-navigate-finish', () => {
    lastFetchedUrl = '';
    lastTrackStatusKey = '';
    if (isVideoPage()) {
      setTimeout(inspectPlayerCaptions, 500);
      setTimeout(inspectPlayerCaptions, 1500);
    }
  });

  window.addEventListener('load', () => {
    if (isVideoPage()) {
      setTimeout(inspectPlayerCaptions, 1000);
    }
  });

  setInterval(inspectPlayerCaptions, 2500);
})();
